// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.nefario.nefario_rpc

@SerialVersionUID(0L)
final case class GetNixFlakeResponse(
    uid: _root_.scala.Predef.String = "",
    name: _root_.scala.Predef.String = "",
    flakeDotNix: _root_.scala.Predef.String = "",
    flakeDotLock: _root_.scala.Predef.String = "",
    changeSeq: _root_.scala.Long = 0L,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[GetNixFlakeResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = uid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = flakeDotNix
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = flakeDotLock
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = changeSeq
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = uid
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = flakeDotNix
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = flakeDotLock
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = changeSeq
        if (__v != 0L) {
          _output__.writeInt64(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withUid(__v: _root_.scala.Predef.String): GetNixFlakeResponse = copy(uid = __v)
    def withName(__v: _root_.scala.Predef.String): GetNixFlakeResponse = copy(name = __v)
    def withFlakeDotNix(__v: _root_.scala.Predef.String): GetNixFlakeResponse = copy(flakeDotNix = __v)
    def withFlakeDotLock(__v: _root_.scala.Predef.String): GetNixFlakeResponse = copy(flakeDotLock = __v)
    def withChangeSeq(__v: _root_.scala.Long): GetNixFlakeResponse = copy(changeSeq = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = uid
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = flakeDotNix
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = flakeDotLock
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = changeSeq
          if (__t != 0L) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(uid)
        case 2 => _root_.scalapb.descriptors.PString(name)
        case 3 => _root_.scalapb.descriptors.PString(flakeDotNix)
        case 4 => _root_.scalapb.descriptors.PString(flakeDotLock)
        case 5 => _root_.scalapb.descriptors.PLong(changeSeq)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse.type = a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse
    // @@protoc_insertion_point(GeneratedMessage[nefario_rpc.GetNixFlakeResponse])
}

object GetNixFlakeResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse = {
    var __uid: _root_.scala.Predef.String = ""
    var __name: _root_.scala.Predef.String = ""
    var __flakeDotNix: _root_.scala.Predef.String = ""
    var __flakeDotLock: _root_.scala.Predef.String = ""
    var __changeSeq: _root_.scala.Long = 0L
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __uid = _input__.readStringRequireUtf8()
        case 18 =>
          __name = _input__.readStringRequireUtf8()
        case 26 =>
          __flakeDotNix = _input__.readStringRequireUtf8()
        case 34 =>
          __flakeDotLock = _input__.readStringRequireUtf8()
        case 40 =>
          __changeSeq = _input__.readInt64()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse(
        uid = __uid,
        name = __name,
        flakeDotNix = __flakeDotNix,
        flakeDotLock = __flakeDotLock,
        changeSeq = __changeSeq,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse(
        uid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        flakeDotNix = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        flakeDotLock = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        changeSeq = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Long]).getOrElse(0L)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = NefarioRpcProto.javaDescriptor.getMessageTypes().get(22)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = NefarioRpcProto.scalaDescriptor.messages(22)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse(
    uid = "",
    name = "",
    flakeDotNix = "",
    flakeDotLock = "",
    changeSeq = 0L
  )
  implicit class GetNixFlakeResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse](_l) {
    def uid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.uid)((c_, f_) => c_.copy(uid = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def flakeDotNix: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.flakeDotNix)((c_, f_) => c_.copy(flakeDotNix = f_))
    def flakeDotLock: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.flakeDotLock)((c_, f_) => c_.copy(flakeDotLock = f_))
    def changeSeq: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.changeSeq)((c_, f_) => c_.copy(changeSeq = f_))
  }
  final val UID_FIELD_NUMBER = 1
  final val NAME_FIELD_NUMBER = 2
  final val FLAKEDOTNIX_FIELD_NUMBER = 3
  final val FLAKEDOTLOCK_FIELD_NUMBER = 4
  final val CHANGESEQ_FIELD_NUMBER = 5
  def of(
    uid: _root_.scala.Predef.String,
    name: _root_.scala.Predef.String,
    flakeDotNix: _root_.scala.Predef.String,
    flakeDotLock: _root_.scala.Predef.String,
    changeSeq: _root_.scala.Long
  ): _root_.a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse = _root_.a8.hermes.proto.nefario.nefario_rpc.GetNixFlakeResponse(
    uid,
    name,
    flakeDotNix,
    flakeDotLock,
    changeSeq
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[nefario_rpc.GetNixFlakeResponse])
}
