// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.checkpoint.checkpoint

/** RunProgram asks the checkpoint mesh worker to run the checkpoint (.cp) program
  * bound to event_kind, handing it the lifecycle happening as payload. This is the
  * Go→checkpoint leg of the event-stream → checker pipeline: the checkpoint-runner
  * (godev) consumes event.lifecycle.* and forwards each matched event here.
  *
  * payload_json is the lifecycle Envelope (eventUid, scheduleUid, eventKind,
  * payload{schedule,event,processRun,disposition}) as JSON — self-contained so the
  * .cp program needs no reload. The worker resolves event_kind → program; in
  * Phase 3 it acknowledges receipt (real .cp healthchecks programs land in Phase 4).
  *
  * @param eventKind
  *   e.g. "run.completed", "run.overdue"
  * @param scheduleUid
  *   convenience; also present inside payload_json
  * @param eventUid
  *   convenience; correlates to the source happening
  * @param payloadJson
  *   the lifecycle Envelope, JSON-encoded
  */
@SerialVersionUID(0L)
final case class RunProgramRequest(
    eventKind: _root_.scala.Predef.String = "",
    scheduleUid: _root_.scala.Predef.String = "",
    eventUid: _root_.scala.Predef.String = "",
    payloadJson: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[RunProgramRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = eventKind
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = scheduleUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = eventUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = payloadJson
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = eventKind
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = scheduleUid
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = eventUid
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = payloadJson
        if (!__v.isEmpty) {
          _output__.writeBytes(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withEventKind(__v: _root_.scala.Predef.String): RunProgramRequest = copy(eventKind = __v)
    def withScheduleUid(__v: _root_.scala.Predef.String): RunProgramRequest = copy(scheduleUid = __v)
    def withEventUid(__v: _root_.scala.Predef.String): RunProgramRequest = copy(eventUid = __v)
    def withPayloadJson(__v: _root_.com.google.protobuf.ByteString): RunProgramRequest = copy(payloadJson = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = eventKind
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = scheduleUid
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = eventUid
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = payloadJson
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(eventKind)
        case 2 => _root_.scalapb.descriptors.PString(scheduleUid)
        case 3 => _root_.scalapb.descriptors.PString(eventUid)
        case 4 => _root_.scalapb.descriptors.PByteString(payloadJson)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest.type = a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest
    // @@protoc_insertion_point(GeneratedMessage[checkpoint_rpc.RunProgramRequest])
}

object RunProgramRequest extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest = {
    var __eventKind: _root_.scala.Predef.String = ""
    var __scheduleUid: _root_.scala.Predef.String = ""
    var __eventUid: _root_.scala.Predef.String = ""
    var __payloadJson: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __eventKind = _input__.readStringRequireUtf8()
        case 18 =>
          __scheduleUid = _input__.readStringRequireUtf8()
        case 26 =>
          __eventUid = _input__.readStringRequireUtf8()
        case 34 =>
          __payloadJson = _input__.readBytes()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest(
        eventKind = __eventKind,
        scheduleUid = __scheduleUid,
        eventUid = __eventUid,
        payloadJson = __payloadJson,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest(
        eventKind = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        scheduleUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        eventUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        payloadJson = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = CheckpointProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = CheckpointProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest(
    eventKind = "",
    scheduleUid = "",
    eventUid = "",
    payloadJson = _root_.com.google.protobuf.ByteString.EMPTY
  )
  implicit class RunProgramRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest](_l) {
    def eventKind: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.eventKind)((c_, f_) => c_.copy(eventKind = f_))
    def scheduleUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.scheduleUid)((c_, f_) => c_.copy(scheduleUid = f_))
    def eventUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.eventUid)((c_, f_) => c_.copy(eventUid = f_))
    def payloadJson: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.payloadJson)((c_, f_) => c_.copy(payloadJson = f_))
  }
  final val EVENT_KIND_FIELD_NUMBER = 1
  final val SCHEDULE_UID_FIELD_NUMBER = 2
  final val EVENT_UID_FIELD_NUMBER = 3
  final val PAYLOAD_JSON_FIELD_NUMBER = 4
  def of(
    eventKind: _root_.scala.Predef.String,
    scheduleUid: _root_.scala.Predef.String,
    eventUid: _root_.scala.Predef.String,
    payloadJson: _root_.com.google.protobuf.ByteString
  ): _root_.a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest = _root_.a8.hermes.proto.checkpoint.checkpoint.RunProgramRequest(
    eventKind,
    scheduleUid,
    eventUid,
    payloadJson
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[checkpoint_rpc.RunProgramRequest])
}
