// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.db.db

/** CatalogJoin is a join the firewall already knows how to make. Telling the model these exist
  * keeps it from guessing at foreign-key names.
  */
@SerialVersionUID(0L)
final case class CatalogJoin(
    joinName: _root_.scala.Predef.String = "",
    toTable: _root_.scala.Predef.String = "",
    joinExpression: _root_.scala.Predef.String = "",
    joinType: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[CatalogJoin] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = joinName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = toTable
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = joinExpression
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = joinType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = joinName
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = toTable
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = joinExpression
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = joinType
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withJoinName(__v: _root_.scala.Predef.String): CatalogJoin = copy(joinName = __v)
    def withToTable(__v: _root_.scala.Predef.String): CatalogJoin = copy(toTable = __v)
    def withJoinExpression(__v: _root_.scala.Predef.String): CatalogJoin = copy(joinExpression = __v)
    def withJoinType(__v: _root_.scala.Predef.String): CatalogJoin = copy(joinType = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = joinName
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = toTable
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = joinExpression
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = joinType
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(joinName)
        case 2 => _root_.scalapb.descriptors.PString(toTable)
        case 3 => _root_.scalapb.descriptors.PString(joinExpression)
        case 4 => _root_.scalapb.descriptors.PString(joinType)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.db.db.CatalogJoin.type = a8.hermes.proto.db.db.CatalogJoin
    // @@protoc_insertion_point(GeneratedMessage[db.CatalogJoin])
}

object CatalogJoin extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.CatalogJoin] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.CatalogJoin] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.db.db.CatalogJoin = {
    var __joinName: _root_.scala.Predef.String = ""
    var __toTable: _root_.scala.Predef.String = ""
    var __joinExpression: _root_.scala.Predef.String = ""
    var __joinType: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __joinName = _input__.readStringRequireUtf8()
        case 18 =>
          __toTable = _input__.readStringRequireUtf8()
        case 26 =>
          __joinExpression = _input__.readStringRequireUtf8()
        case 34 =>
          __joinType = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.db.db.CatalogJoin(
        joinName = __joinName,
        toTable = __toTable,
        joinExpression = __joinExpression,
        joinType = __joinType,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.db.db.CatalogJoin] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.db.db.CatalogJoin(
        joinName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        toTable = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        joinExpression = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        joinType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = DbProto.javaDescriptor.getMessageTypes().get(27)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = DbProto.scalaDescriptor.messages(27)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.db.db.CatalogJoin(
    joinName = "",
    toTable = "",
    joinExpression = "",
    joinType = ""
  )
  implicit class CatalogJoinLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.db.db.CatalogJoin]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.db.db.CatalogJoin](_l) {
    def joinName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.joinName)((c_, f_) => c_.copy(joinName = f_))
    def toTable: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.toTable)((c_, f_) => c_.copy(toTable = f_))
    def joinExpression: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.joinExpression)((c_, f_) => c_.copy(joinExpression = f_))
    def joinType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.joinType)((c_, f_) => c_.copy(joinType = f_))
  }
  final val JOIN_NAME_FIELD_NUMBER = 1
  final val TO_TABLE_FIELD_NUMBER = 2
  final val JOIN_EXPRESSION_FIELD_NUMBER = 3
  final val JOIN_TYPE_FIELD_NUMBER = 4
  def of(
    joinName: _root_.scala.Predef.String,
    toTable: _root_.scala.Predef.String,
    joinExpression: _root_.scala.Predef.String,
    joinType: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.db.db.CatalogJoin = _root_.a8.hermes.proto.db.db.CatalogJoin(
    joinName,
    toTable,
    joinExpression,
    joinType
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[db.CatalogJoin])
}
