// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.db.db

/** DeleteRequest deletes row(s)
  *
  * @param tableName
  *   Target table
  * @param key
  *   Primary key to delete (required for safety)
  * @param softDelete
  *   If true, set deleted_at instead of DELETE
  */
@SerialVersionUID(0L)
final case class DeleteRequest(
    tableName: _root_.scala.Predef.String = "",
    key: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None,
    softDelete: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[DeleteRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = tableName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (key.isDefined) {
        val __value = key.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = softDelete
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = tableName
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      key.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = softDelete
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withTableName(__v: _root_.scala.Predef.String): DeleteRequest = copy(tableName = __v)
    def getKey: com.google.protobuf.struct.Struct = key.getOrElse(com.google.protobuf.struct.Struct.defaultInstance)
    def clearKey: DeleteRequest = copy(key = _root_.scala.None)
    def withKey(__v: com.google.protobuf.struct.Struct): DeleteRequest = copy(key = Option(__v))
    def withSoftDelete(__v: _root_.scala.Boolean): DeleteRequest = copy(softDelete = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = tableName
          if (__t != "") __t else null
        }
        case 2 => key.orNull
        case 3 => {
          val __t = softDelete
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(tableName)
        case 2 => key.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => _root_.scalapb.descriptors.PBoolean(softDelete)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.db.db.DeleteRequest.type = a8.hermes.proto.db.db.DeleteRequest
    // @@protoc_insertion_point(GeneratedMessage[db.DeleteRequest])
}

object DeleteRequest extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.DeleteRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.DeleteRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.db.db.DeleteRequest = {
    var __tableName: _root_.scala.Predef.String = ""
    var __key: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None
    var __softDelete: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __tableName = _input__.readStringRequireUtf8()
        case 18 =>
          __key = _root_.scala.Option(__key.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.struct.Struct](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 24 =>
          __softDelete = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.db.db.DeleteRequest(
        tableName = __tableName,
        key = __key,
        softDelete = __softDelete,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.db.db.DeleteRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.db.db.DeleteRequest(
        tableName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.struct.Struct]]),
        softDelete = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = DbProto.javaDescriptor.getMessageTypes().get(9)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = DbProto.scalaDescriptor.messages(9)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.google.protobuf.struct.Struct
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.db.db.DeleteRequest(
    tableName = "",
    key = _root_.scala.None,
    softDelete = false
  )
  implicit class DeleteRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.db.db.DeleteRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.db.db.DeleteRequest](_l) {
    def tableName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.tableName)((c_, f_) => c_.copy(tableName = f_))
    def key: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.struct.Struct] = field(_.getKey)((c_, f_) => c_.copy(key = _root_.scala.Option(f_)))
    def optionalKey: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.struct.Struct]] = field(_.key)((c_, f_) => c_.copy(key = f_))
    def softDelete: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.softDelete)((c_, f_) => c_.copy(softDelete = f_))
  }
  final val TABLE_NAME_FIELD_NUMBER = 1
  final val KEY_FIELD_NUMBER = 2
  final val SOFT_DELETE_FIELD_NUMBER = 3
  def of(
    tableName: _root_.scala.Predef.String,
    key: _root_.scala.Option[com.google.protobuf.struct.Struct],
    softDelete: _root_.scala.Boolean
  ): _root_.a8.hermes.proto.db.db.DeleteRequest = _root_.a8.hermes.proto.db.db.DeleteRequest(
    tableName,
    key,
    softDelete
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[db.DeleteRequest])
}
