// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.db.db

/** @param actualTableName
  *   Empty if same as table_name
  */
@SerialVersionUID(0L)
final case class ExplainTableMetadata(
    uid: _root_.scala.Predef.String = "",
    tableName: _root_.scala.Predef.String = "",
    actualTableName: _root_.scala.Predef.String = "",
    schemaName: _root_.scala.Predef.String = "",
    description: _root_.scala.Predef.String = "",
    primaryKeys: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ExplainTableMetadata] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = uid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = tableName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = actualTableName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = schemaName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = description
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      primaryKeys.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = uid
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = tableName
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = actualTableName
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = schemaName
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = description
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      primaryKeys.foreach { __v =>
        val __m = __v
        _output__.writeString(9, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def withUid(__v: _root_.scala.Predef.String): ExplainTableMetadata = copy(uid = __v)
    def withTableName(__v: _root_.scala.Predef.String): ExplainTableMetadata = copy(tableName = __v)
    def withActualTableName(__v: _root_.scala.Predef.String): ExplainTableMetadata = copy(actualTableName = __v)
    def withSchemaName(__v: _root_.scala.Predef.String): ExplainTableMetadata = copy(schemaName = __v)
    def withDescription(__v: _root_.scala.Predef.String): ExplainTableMetadata = copy(description = __v)
    def clearPrimaryKeys = copy(primaryKeys = _root_.scala.Seq.empty)
    def addPrimaryKeys(__vs: _root_.scala.Predef.String *): ExplainTableMetadata = addAllPrimaryKeys(__vs)
    def addAllPrimaryKeys(__vs: Iterable[_root_.scala.Predef.String]): ExplainTableMetadata = copy(primaryKeys = primaryKeys ++ __vs)
    def withPrimaryKeys(__v: _root_.scala.Seq[_root_.scala.Predef.String]): ExplainTableMetadata = copy(primaryKeys = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = uid
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = tableName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = actualTableName
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = schemaName
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = description
          if (__t != "") __t else null
        }
        case 9 => primaryKeys
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(uid)
        case 2 => _root_.scalapb.descriptors.PString(tableName)
        case 3 => _root_.scalapb.descriptors.PString(actualTableName)
        case 4 => _root_.scalapb.descriptors.PString(schemaName)
        case 5 => _root_.scalapb.descriptors.PString(description)
        case 9 => _root_.scalapb.descriptors.PRepeated(primaryKeys.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.db.db.ExplainTableMetadata.type = a8.hermes.proto.db.db.ExplainTableMetadata
    // @@protoc_insertion_point(GeneratedMessage[db.ExplainTableMetadata])
}

object ExplainTableMetadata extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.ExplainTableMetadata] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.ExplainTableMetadata] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.db.db.ExplainTableMetadata = {
    var __uid: _root_.scala.Predef.String = ""
    var __tableName: _root_.scala.Predef.String = ""
    var __actualTableName: _root_.scala.Predef.String = ""
    var __schemaName: _root_.scala.Predef.String = ""
    var __description: _root_.scala.Predef.String = ""
    val __primaryKeys: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __uid = _input__.readStringRequireUtf8()
        case 18 =>
          __tableName = _input__.readStringRequireUtf8()
        case 26 =>
          __actualTableName = _input__.readStringRequireUtf8()
        case 34 =>
          __schemaName = _input__.readStringRequireUtf8()
        case 42 =>
          __description = _input__.readStringRequireUtf8()
        case 74 =>
          __primaryKeys += _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.db.db.ExplainTableMetadata(
        uid = __uid,
        tableName = __tableName,
        actualTableName = __actualTableName,
        schemaName = __schemaName,
        description = __description,
        primaryKeys = __primaryKeys.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.db.db.ExplainTableMetadata] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.db.db.ExplainTableMetadata(
        uid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        tableName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        actualTableName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        schemaName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        primaryKeys = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = DbProto.javaDescriptor.getMessageTypes().get(17)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = DbProto.scalaDescriptor.messages(17)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.db.db.ExplainTableMetadata(
    uid = "",
    tableName = "",
    actualTableName = "",
    schemaName = "",
    description = "",
    primaryKeys = _root_.scala.Seq.empty
  )
  implicit class ExplainTableMetadataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.db.db.ExplainTableMetadata]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.db.db.ExplainTableMetadata](_l) {
    def uid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.uid)((c_, f_) => c_.copy(uid = f_))
    def tableName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.tableName)((c_, f_) => c_.copy(tableName = f_))
    def actualTableName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.actualTableName)((c_, f_) => c_.copy(actualTableName = f_))
    def schemaName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.schemaName)((c_, f_) => c_.copy(schemaName = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
    def primaryKeys: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.primaryKeys)((c_, f_) => c_.copy(primaryKeys = f_))
  }
  final val UID_FIELD_NUMBER = 1
  final val TABLE_NAME_FIELD_NUMBER = 2
  final val ACTUAL_TABLE_NAME_FIELD_NUMBER = 3
  final val SCHEMA_NAME_FIELD_NUMBER = 4
  final val DESCRIPTION_FIELD_NUMBER = 5
  final val PRIMARY_KEYS_FIELD_NUMBER = 9
  def of(
    uid: _root_.scala.Predef.String,
    tableName: _root_.scala.Predef.String,
    actualTableName: _root_.scala.Predef.String,
    schemaName: _root_.scala.Predef.String,
    description: _root_.scala.Predef.String,
    primaryKeys: _root_.scala.Seq[_root_.scala.Predef.String]
  ): _root_.a8.hermes.proto.db.db.ExplainTableMetadata = _root_.a8.hermes.proto.db.db.ExplainTableMetadata(
    uid,
    tableName,
    actualTableName,
    schemaName,
    description,
    primaryKeys
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[db.ExplainTableMetadata])
}
