// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.db.db

/** @param name
  *   Lowercased column name for lookups
  * @param label
  *   Original-case column name for display
  */
@SerialVersionUID(0L)
final case class QueryColumnMetadata(
    name: _root_.scala.Predef.String = "",
    label: _root_.scala.Predef.String = "",
    sqlType: _root_.scala.Predef.String = "",
    nullable: _root_.scala.Boolean = false,
    dataTypeSize: _root_.scala.Int = 0,
    typeModifier: _root_.scala.Int = 0,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[QueryColumnMetadata] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = label
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = sqlType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = nullable
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      
      {
        val __value = dataTypeSize
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(4, __value)
        }
      };
      
      {
        val __value = typeModifier
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = sqlType
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = nullable
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      {
        val __v = dataTypeSize
        if (__v != 0) {
          _output__.writeInt32(4, __v)
        }
      };
      {
        val __v = typeModifier
        if (__v != 0) {
          _output__.writeInt32(5, __v)
        }
      };
      {
        val __v = label
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withName(__v: _root_.scala.Predef.String): QueryColumnMetadata = copy(name = __v)
    def withLabel(__v: _root_.scala.Predef.String): QueryColumnMetadata = copy(label = __v)
    def withSqlType(__v: _root_.scala.Predef.String): QueryColumnMetadata = copy(sqlType = __v)
    def withNullable(__v: _root_.scala.Boolean): QueryColumnMetadata = copy(nullable = __v)
    def withDataTypeSize(__v: _root_.scala.Int): QueryColumnMetadata = copy(dataTypeSize = __v)
    def withTypeModifier(__v: _root_.scala.Int): QueryColumnMetadata = copy(typeModifier = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = label
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = sqlType
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = nullable
          if (__t != false) __t else null
        }
        case 4 => {
          val __t = dataTypeSize
          if (__t != 0) __t else null
        }
        case 5 => {
          val __t = typeModifier
          if (__t != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 6 => _root_.scalapb.descriptors.PString(label)
        case 2 => _root_.scalapb.descriptors.PString(sqlType)
        case 3 => _root_.scalapb.descriptors.PBoolean(nullable)
        case 4 => _root_.scalapb.descriptors.PInt(dataTypeSize)
        case 5 => _root_.scalapb.descriptors.PInt(typeModifier)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.db.db.QueryColumnMetadata.type = a8.hermes.proto.db.db.QueryColumnMetadata
    // @@protoc_insertion_point(GeneratedMessage[db.QueryColumnMetadata])
}

object QueryColumnMetadata extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.QueryColumnMetadata] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.db.db.QueryColumnMetadata] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.db.db.QueryColumnMetadata = {
    var __name: _root_.scala.Predef.String = ""
    var __label: _root_.scala.Predef.String = ""
    var __sqlType: _root_.scala.Predef.String = ""
    var __nullable: _root_.scala.Boolean = false
    var __dataTypeSize: _root_.scala.Int = 0
    var __typeModifier: _root_.scala.Int = 0
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __name = _input__.readStringRequireUtf8()
        case 50 =>
          __label = _input__.readStringRequireUtf8()
        case 18 =>
          __sqlType = _input__.readStringRequireUtf8()
        case 24 =>
          __nullable = _input__.readBool()
        case 32 =>
          __dataTypeSize = _input__.readInt32()
        case 40 =>
          __typeModifier = _input__.readInt32()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.db.db.QueryColumnMetadata(
        name = __name,
        label = __label,
        sqlType = __sqlType,
        nullable = __nullable,
        dataTypeSize = __dataTypeSize,
        typeModifier = __typeModifier,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.db.db.QueryColumnMetadata] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.db.db.QueryColumnMetadata(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        label = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        sqlType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        nullable = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        dataTypeSize = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        typeModifier = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Int]).getOrElse(0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = DbProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = DbProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.db.db.QueryColumnMetadata(
    name = "",
    label = "",
    sqlType = "",
    nullable = false,
    dataTypeSize = 0,
    typeModifier = 0
  )
  implicit class QueryColumnMetadataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.db.db.QueryColumnMetadata]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.db.db.QueryColumnMetadata](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def label: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.label)((c_, f_) => c_.copy(label = f_))
    def sqlType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.sqlType)((c_, f_) => c_.copy(sqlType = f_))
    def nullable: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.nullable)((c_, f_) => c_.copy(nullable = f_))
    def dataTypeSize: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.dataTypeSize)((c_, f_) => c_.copy(dataTypeSize = f_))
    def typeModifier: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.typeModifier)((c_, f_) => c_.copy(typeModifier = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val LABEL_FIELD_NUMBER = 6
  final val SQL_TYPE_FIELD_NUMBER = 2
  final val NULLABLE_FIELD_NUMBER = 3
  final val DATA_TYPE_SIZE_FIELD_NUMBER = 4
  final val TYPE_MODIFIER_FIELD_NUMBER = 5
  def of(
    name: _root_.scala.Predef.String,
    label: _root_.scala.Predef.String,
    sqlType: _root_.scala.Predef.String,
    nullable: _root_.scala.Boolean,
    dataTypeSize: _root_.scala.Int,
    typeModifier: _root_.scala.Int
  ): _root_.a8.hermes.proto.db.db.QueryColumnMetadata = _root_.a8.hermes.proto.db.db.QueryColumnMetadata(
    name,
    label,
    sqlType,
    nullable,
    dataTypeSize,
    typeModifier
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[db.QueryColumnMetadata])
}
