// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.fileset.fileset

@SerialVersionUID(0L)
final case class AccessEntry(
    uid: _root_.scala.Predef.String = "",
    usergroupUid: _root_.scala.Predef.String = "",
    perms: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[AccessEntry] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = uid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = usergroupUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = perms
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = uid
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = usergroupUid
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = perms
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withUid(__v: _root_.scala.Predef.String): AccessEntry = copy(uid = __v)
    def withUsergroupUid(__v: _root_.scala.Predef.String): AccessEntry = copy(usergroupUid = __v)
    def withPerms(__v: _root_.scala.Predef.String): AccessEntry = copy(perms = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = uid
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = usergroupUid
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = perms
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(uid)
        case 2 => _root_.scalapb.descriptors.PString(usergroupUid)
        case 3 => _root_.scalapb.descriptors.PString(perms)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.fileset.fileset.AccessEntry.type = a8.hermes.proto.fileset.fileset.AccessEntry
    // @@protoc_insertion_point(GeneratedMessage[fileset.AccessEntry])
}

object AccessEntry extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.fileset.fileset.AccessEntry] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.fileset.fileset.AccessEntry] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.fileset.fileset.AccessEntry = {
    var __uid: _root_.scala.Predef.String = ""
    var __usergroupUid: _root_.scala.Predef.String = ""
    var __perms: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __uid = _input__.readStringRequireUtf8()
        case 18 =>
          __usergroupUid = _input__.readStringRequireUtf8()
        case 26 =>
          __perms = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.fileset.fileset.AccessEntry(
        uid = __uid,
        usergroupUid = __usergroupUid,
        perms = __perms,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.fileset.fileset.AccessEntry] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.fileset.fileset.AccessEntry(
        uid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        usergroupUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        perms = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = FilesetProto.javaDescriptor.getMessageTypes().get(16)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = FilesetProto.scalaDescriptor.messages(16)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.fileset.fileset.AccessEntry(
    uid = "",
    usergroupUid = "",
    perms = ""
  )
  implicit class AccessEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.fileset.fileset.AccessEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.fileset.fileset.AccessEntry](_l) {
    def uid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.uid)((c_, f_) => c_.copy(uid = f_))
    def usergroupUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.usergroupUid)((c_, f_) => c_.copy(usergroupUid = f_))
    def perms: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.perms)((c_, f_) => c_.copy(perms = f_))
  }
  final val UID_FIELD_NUMBER = 1
  final val USERGROUP_UID_FIELD_NUMBER = 2
  final val PERMS_FIELD_NUMBER = 3
  def of(
    uid: _root_.scala.Predef.String,
    usergroupUid: _root_.scala.Predef.String,
    perms: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.fileset.fileset.AccessEntry = _root_.a8.hermes.proto.fileset.fileset.AccessEntry(
    uid,
    usergroupUid,
    perms
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[fileset.AccessEntry])
}
