// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.fileset.fileset

object FilesetProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      a8.hermes.proto.fileset.fileset.CreateFilesetRequest,
      a8.hermes.proto.fileset.fileset.CreateFilesetResponse,
      a8.hermes.proto.fileset.fileset.PullRequest,
      a8.hermes.proto.fileset.fileset.PullResponse,
      a8.hermes.proto.fileset.fileset.PullRevisionRequest,
      a8.hermes.proto.fileset.fileset.PullRevisionResponse,
      a8.hermes.proto.fileset.fileset.PushRequest,
      a8.hermes.proto.fileset.fileset.PushResponse,
      a8.hermes.proto.fileset.fileset.ListFilesetsRequest,
      a8.hermes.proto.fileset.fileset.ListFilesetsResponse,
      a8.hermes.proto.fileset.fileset.GrantAccessRequest,
      a8.hermes.proto.fileset.fileset.GrantAccessResponse,
      a8.hermes.proto.fileset.fileset.ListAccessRequest,
      a8.hermes.proto.fileset.fileset.ListAccessResponse,
      a8.hermes.proto.fileset.fileset.FileEntry,
      a8.hermes.proto.fileset.fileset.FilesetInfo,
      a8.hermes.proto.fileset.fileset.AccessEntry
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ch1wa2cvcnBjL2ZpbGVzZXQvZmlsZXNldC5wcm90bxIHZmlsZXNldCJpChRDcmVhdGVGaWxlc2V0UmVxdWVzdBIdCgRuYW1lG
  AEgASgJQgniPwYSBG5hbWVSBG5hbWUSMgoLZGVzY3JpcHRpb24YAiABKAlCEOI/DRILZGVzY3JpcHRpb25SC2Rlc2NyaXB0aW9uI
  oEBChVDcmVhdGVGaWxlc2V0UmVzcG9uc2USMAoLZmlsZXNldF91aWQYASABKAlCD+I/DBIKZmlsZXNldFVpZFIKZmlsZXNldFVpZ
  BI2Cg1lcnJvcl9tZXNzYWdlGAIgASgJQhHiPw4SDGVycm9yTWVzc2FnZVIMZXJyb3JNZXNzYWdlIkIKC1B1bGxSZXF1ZXN0EjMKD
  GZpbGVzZXRfbmFtZRgBIAEoCUIQ4j8NEgtmaWxlc2V0TmFtZVILZmlsZXNldE5hbWUiyQIKDFB1bGxSZXNwb25zZRIwCgtmaWxlc
  2V0X3VpZBgBIAEoCUIP4j8MEgpmaWxlc2V0VWlkUgpmaWxlc2V0VWlkEjMKDGZpbGVzZXRfbmFtZRgCIAEoCUIQ4j8NEgtmaWxlc
  2V0TmFtZVILZmlsZXNldE5hbWUSMwoMcmV2aXNpb25fdWlkGAMgASgJQhDiPw0SC3JldmlzaW9uVWlkUgtyZXZpc2lvblVpZBI6C
  gdlbnRyaWVzGAQgAygLMhIuZmlsZXNldC5GaWxlRW50cnlCDOI/CRIHZW50cmllc1IHZW50cmllcxI2Cg1lcnJvcl9tZXNzYWdlG
  AUgASgJQhHiPw4SDGVycm9yTWVzc2FnZVIMZXJyb3JNZXNzYWdlEikKCHNldHRpbmdzGAYgASgJQg3iPwoSCHNldHRpbmdzUghzZ
  XR0aW5ncyJ8ChNQdWxsUmV2aXNpb25SZXF1ZXN0EjAKC2ZpbGVzZXRfdWlkGAEgASgJQg/iPwwSCmZpbGVzZXRVaWRSCmZpbGVzZ
  XRVaWQSMwoMcmV2aXNpb25fdWlkGAIgASgJQhDiPw0SC3JldmlzaW9uVWlkUgtyZXZpc2lvblVpZCKmAgoUUHVsbFJldmlzaW9uU
  mVzcG9uc2USMAoLZmlsZXNldF91aWQYASABKAlCD+I/DBIKZmlsZXNldFVpZFIKZmlsZXNldFVpZBIzCgxmaWxlc2V0X25hbWUYA
  iABKAlCEOI/DRILZmlsZXNldE5hbWVSC2ZpbGVzZXROYW1lEjMKDHJldmlzaW9uX3VpZBgDIAEoCUIQ4j8NEgtyZXZpc2lvblVpZ
  FILcmV2aXNpb25VaWQSOgoHZW50cmllcxgEIAMoCzISLmZpbGVzZXQuRmlsZUVudHJ5QgziPwkSB2VudHJpZXNSB2VudHJpZXMSN
  goNZXJyb3JfbWVzc2FnZRgFIAEoCUIR4j8OEgxlcnJvck1lc3NhZ2VSDGVycm9yTWVzc2FnZSKcAgoLUHVzaFJlcXVlc3QSMAoLZ
  mlsZXNldF91aWQYASABKAlCD+I/DBIKZmlsZXNldFVpZFIKZmlsZXNldFVpZBJMChVleHBlY3RlZF9yZXZpc2lvbl91aWQYAiABK
  AlCGOI/FRITZXhwZWN0ZWRSZXZpc2lvblVpZFITZXhwZWN0ZWRSZXZpc2lvblVpZBI6CgdlbnRyaWVzGAMgAygLMhIuZmlsZXNld
  C5GaWxlRW50cnlCDOI/CRIHZW50cmllc1IHZW50cmllcxImCgdtZXNzYWdlGAQgASgJQgziPwkSB21lc3NhZ2VSB21lc3NhZ2USK
  QoIc2V0dGluZ3MYBSABKAlCDeI/ChIIc2V0dGluZ3NSCHNldHRpbmdzItgBCgxQdXNoUmVzcG9uc2USPQoQbmV3X3JldmlzaW9uX
  3VpZBgBIAEoCUIT4j8QEg5uZXdSZXZpc2lvblVpZFIObmV3UmV2aXNpb25VaWQSJgoHc3VjY2VzcxgCIAEoCEIM4j8JEgdzdWNjZ
  XNzUgdzdWNjZXNzEikKCGNvbmZsaWN0GAMgASgIQg3iPwoSCGNvbmZsaWN0Ughjb25mbGljdBI2Cg1lcnJvcl9tZXNzYWdlGAQgA
  SgJQhHiPw4SDGVycm9yTWVzc2FnZVIMZXJyb3JNZXNzYWdlIhUKE0xpc3RGaWxlc2V0c1JlcXVlc3QiVwoUTGlzdEZpbGVzZXRzU
  mVzcG9uc2USPwoIZmlsZXNldHMYASADKAsyFC5maWxlc2V0LkZpbGVzZXRJbmZvQg3iPwoSCGZpbGVzZXRzUghmaWxlc2V0cyKgA
  QoSR3JhbnRBY2Nlc3NSZXF1ZXN0EjAKC2ZpbGVzZXRfdWlkGAEgASgJQg/iPwwSCmZpbGVzZXRVaWRSCmZpbGVzZXRVaWQSNgoNd
  XNlcmdyb3VwX3VpZBgCIAEoCUIR4j8OEgx1c2VyZ3JvdXBVaWRSDHVzZXJncm91cFVpZBIgCgVwZXJtcxgDIAEoCUIK4j8HEgVwZ
  XJtc1IFcGVybXMidQoTR3JhbnRBY2Nlc3NSZXNwb25zZRImCgdzdWNjZXNzGAEgASgIQgziPwkSB3N1Y2Nlc3NSB3N1Y2Nlc3MSN
  goNZXJyb3JfbWVzc2FnZRgCIAEoCUIR4j8OEgxlcnJvck1lc3NhZ2VSDGVycm9yTWVzc2FnZSJFChFMaXN0QWNjZXNzUmVxdWVzd
  BIwCgtmaWxlc2V0X3VpZBgBIAEoCUIP4j8MEgpmaWxlc2V0VWlkUgpmaWxlc2V0VWlkIlIKEkxpc3RBY2Nlc3NSZXNwb25zZRI8C
  gdlbnRyaWVzGAEgAygLMhQuZmlsZXNldC5BY2Nlc3NFbnRyeUIM4j8JEgdlbnRyaWVzUgdlbnRyaWVzIpYBCglGaWxlRW50cnkSH
  QoEcGF0aBgBIAEoCUIJ4j8GEgRwYXRoUgRwYXRoEiMKBnNoYTI1NhgCIAEoCUIL4j8IEgZzaGEyNTZSBnNoYTI1NhIdCgRzaXplG
  AMgASgDQgniPwYSBHNpemVSBHNpemUSJgoHY29udGVudBgEIAEoDEIM4j8JEgdjb250ZW50Ugdjb250ZW50Ir0BCgtGaWxlc2V0S
  W5mbxIaCgN1aWQYASABKAlCCOI/BRIDdWlkUgN1aWQSHQoEbmFtZRgCIAEoCUIJ4j8GEgRuYW1lUgRuYW1lEjIKC2Rlc2NyaXB0a
  W9uGAMgASgJQhDiPw0SC2Rlc2NyaXB0aW9uUgtkZXNjcmlwdGlvbhI/ChBjdXJyZW50X3JldmlzaW9uGAQgASgJQhTiPxESD2N1c
  nJlbnRSZXZpc2lvblIPY3VycmVudFJldmlzaW9uIoMBCgtBY2Nlc3NFbnRyeRIaCgN1aWQYASABKAlCCOI/BRIDdWlkUgN1aWQSN
  goNdXNlcmdyb3VwX3VpZBgCIAEoCUIR4j8OEgx1c2VyZ3JvdXBVaWRSDHVzZXJncm91cFVpZBIgCgVwZXJtcxgDIAEoCUIK4j8HE
  gVwZXJtc1IFcGVybXNCPAoXYTguaGVybWVzLnByb3RvLmZpbGVzZXRQAVofYWNjdXI4LmlvL2dvZGV2L3BrZy9ycGMvZmlsZXNld
  GIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}