
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2022-01-31T17:26:05.981685900 by glen on fullfillment
// 
// a8-versions build/versioning info follows
// 
// 
// 
//

val appVersion = a8.sbt_a8.versionStamp(file("."))

// See the hermes project for why the wsconform harness needs the classpath as a file.
val wsconformClasspath = taskKey[File]("write hermes's runtime classpath for the wsconform harness")

val scalaLibVersion = "3.8.4"
//val zioVersion = "2.0.19"
//val zioLoggingVersion = "2.1.15"
val slf4jVersion = "2.0.9"
//val zeroWasteVersion = "0.2.15"
val logbackVersion = "1.4.14"

//val zeroWastePlugin = compilerPlugin("com.github.ghik" % "zerowaste" % zeroWasteVersion cross CrossVersion.full)

ThisBuild / javacOptions ++= Seq(
//  "-source", "23",
//  "-target", "23"
)

Global / resolvers += {
  try {
    "a8-repo" at Common.readRepoUrl()
  } catch {
    case e: RuntimeException =>
      val log = sLog.value
      log.warn(s"WARNING: a8-repo not found, using default maven repo -- ${e.getMessage}")
      "Oracle Repository" at "https://download.oracle.com/maven"
  }
}

Global / publishTo := {
  try {
    Some("a8-repo-releases" at Common.readRepoUrl())
  } catch {
    case e: RuntimeException =>
      val log = sLog.value
      log.warn(s"WARNING: no publishTo configured -- ${e.getMessage}")
      None
  }
}

Global / credentials ++= {
  try {
    Some(Common.readRepoCredentials())
  } catch {
    case e: RuntimeException =>
      val log = sLog.value
      log.warn(s"WARNING: no credentials configured -- ${e.getMessage}")
      None
  }
}

// Global / publishTo := sonatypePublishToBundle.value
// Global / credentials += Credentials(Path.userHome / ".sbt" / "sonatype.credentials")

Global / scalaVersion := scalaLibVersion

Global / organization := "io.accur8"

Global / version := appVersion

Global / versionScheme := Some("strict")

Global / serverConnectionType := ConnectionType.Local

//Global / scalacOptions ++= Seq(
//  "-deprecation",
//  "-feature",
//  "-unchecked",
//  "-language:higherKinds",
//  "-language:implicitConversions",
//  "-language:strictEquality",
//  "-Xfatal-warnings",
//  "-Xlint",
//  "-Yinline-warnings",
//  "-Yno-adapted-args",
//  "-Ywarn-dead-code",
//  "-Ywarn-numeric-widen",
//  "-Ywarn-value-discard",
//  "-Xfuture",
////  "-Ywarn-unused-import"
//)
// Files where scalac reports a GIVEN import as unused when it is not.
//
// -language:strictEquality is on below, so the CanEqual givens brought in by
// SharedImports.canEqual.given are what make every == typecheck. scalac's unused-import
// analysis does not credit them, and deleting one does not warn -- it fails with
//
//     [E172] Values of types X and Y cannot be compared with == or !=
//
// at each comparison site. Measured during the squash: removing all 14 flagged given
// imports produced 11 E172 errors across 5 files.
//
// The cost of this list is real: -Wconf cannot tell a given import from an ordinary one,
// so these files lose genuine unused-import enforcement too. Keep it short, and delete
// entries as the underlying scalac behaviour is fixed. The durable fix is to put those
// CanEqual instances in implicit scope so no import is needed -- see
// FEATURE-20260804-canequal-givens-into-implicit-scope.
val givenImportFalsePositives = Seq(
  "a8/hermes/nats/MxNatsMailboxClient",
  "a8/shared/CascadingHocon",
  "a8/shared/HoconOps",
  "a8/shared/IntValue",
  "a8/shared/LongValue",
  "a8/shared/NumberValue",
  "a8/shared/StringValue",
  "a8/shared/jdbcf/JdbcErrorClassifier",
  "a8/shared/jdbcf/RowReader",
  "a8/shared/jdbcf/mapper/ComponentMapper",
  "a8/shared/jdbcf/mapper/KeyedTableMapper",
  "a8/shared/jdbcf/unsafe",
  "a8/shared/json/impl/JsonTypedCodecs",
  "a8/shared/json/JsonTest",
  "a8/shared/json/JsonTypedCodecTest",
  "a8/sync/http/http",
  "a8/sync/http/impl/impl",
  "a8/sync/http/impl/RequestImpl",
  "a8/sync/http/impl/RequestProcessorImpl",
  "playground/HoconDemo",
)

Global / scalacOptions ++= Seq(
  // "-encoding", "UTF-8",
  "-deprecation",
  "-feature",
  "-unchecked",
  "-language:implicitConversions",
  "-language:higherKinds",
  "-language:existentials",
  "-language:postfixOps",
  "-language:strictEquality",
  "-Werror",
  // Still deliberately NOT -Wunused:all -- `all` would add `implicits`, which we measured
  // and rejected (TASK-20260804-sync-wunused-params). The two parameter categories are not
  // alike:
  //
  // explicits IS on. All 13 sites were genuinely dead, and four were defects a reader would
  // not have found: LoggingBootstrapConfig.finalizeConfig took an
  // applySystemPropertyOverrides flag it never consulted; ServiceDiscovery.autoRegister
  // dropped its capabilities argument; resultSetToStream took a chunkSize that StreamingQuery
  // dutifully passed into a void; and HoconOps ConfigValueOps.readPath ignored its path and
  // decoded the whole object. In this category "unused" really does mean dead.
  //
  // implicits is OFF and should stay off. 27 sites, and after discounting the ones that are
  // simply vestigial the remainder is context propagation (`using Ctx`, `using Logger`) and
  // type-class evidence required for CONSTRUCTION rather than for the body -- the
  // JsonCodec bounds on QubesMapperBuilder's CompositePrimaryKey2/3/4 are unused in those
  // case classes, but deleting them only relocates the warning onto the public trait methods
  // that forward them. Enforcing buys permanent @unused noise on ~11 signatures and catches
  // nothing, because in this category "unused" does not mean dead.
  "-Wunused:imports,privates,locals,patvars,explicits",
  s"-Wconf:msg=unused import&src=.*/(${givenImportFalsePositives.mkString("|")})\\.scala:s",
)

lazy val logging =
  Common
    .crossProject("a8-logging", file("logging"), "logging")
    .settings(
      libraryDependencies ++= Seq(
        "com.lihaoyi" %%% "sourcecode" % "0.3.0",
//        "dev.zio" %%% "zio" % zioVersion,
//        "dev.zio" %% "zio-logging" % zioLoggingVersion,
//        zeroWastePlugin,
      )
    )
    .jvmSettings(
      libraryDependencies ++= Seq(
        "org.slf4j" % "slf4j-api" % slf4jVersion,
//        "dev.zio" %% "zio-logging-slf4j2" % zioLoggingVersion,
      )
    )
    .jsSettings(
      libraryDependencies ++= Seq(
        "org.scala-js" %%% "scalajs-dom" % "2.6.0",
      )
    )

lazy val loggingJVM = logging.jvm
//lazy val loggingJS = logging.js

lazy val logging_logback =
  Common
    .jvmProject("a8-logging-logback", file("logging_logback"), "logging_logback")
    .dependsOn(loggingJVM)
    .settings(
      libraryDependencies ++= Seq(
//        zeroWastePlugin,
      )
    )
    .settings(
      libraryDependencies ++= Seq(
        "org.codehaus.janino" % "janino" % "3.1.8",
        "org.fusesource.jansi" % "jansi" % "2.4.0",
        "ch.qos.logback" % "logback-core" % logbackVersion,
        "ch.qos.logback" % "logback-classic" % logbackVersion,
        "org.slf4j" % "jcl-over-slf4j" % slf4jVersion,
        "org.slf4j" % "jul-to-slf4j" % slf4jVersion,
      )
    )

lazy val logging_logback_test =
  Common
    .jvmProject("a8-logging-logback_test", file("logging_logback_test"), "logging_logback_test")
    .dependsOn(logging_logback)

//lazy val api =
//  Common
//    .jvmProject("a8-sync-api", file("api"), "api")
//    .dependsOn(shared)
//    .settings(
////      testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
//      libraryDependencies ++= Seq(
//        "org.scalatest" %% "scalatest" % "3.2.15" % "test",
////        zeroWastePlugin,
//      )
//    )

//lazy val http =
//  Common
//    .jvmProject("a8-http-server", file("http-server"), "http-server")
//    .dependsOn(api)
//    .settings(
////      testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
//      libraryDependencies ++= Seq(
////        "dev.zio" %% "zio-http" % "3.0.0-RC1",
//        "org.scalatest" %% "scalatest" % "3.2.15" % "test",
////        zeroWastePlugin,
//      )
//    )

lazy val nats =
  Common
    .jvmProject("a8-nats", file("nats"), "nats")
    .dependsOn(shared)
    .settings(
      libraryDependencies ++= Seq(
        "io.nats" % "jnats" % "2.20.6",
        "com.github.luben" % "zstd-jni" % "1.5.6-8",
        "org.scalatest" %% "scalatest" % "3.2.15" % "test",
      )
    )

lazy val hermesProto =
  Common
    .jvmProject("a8-hermes-proto", file("hermes-proto"), "hermesProto")
    .settings(
      // Disable strict equality and all warnings for generated protobuf code
      scalacOptions := scalacOptions.value.filterNot(_ == "-language:strictEquality") :+ "-Wconf:any:silent",
      // ScalaPB runtime dependency for generated code
      // Proto generation is done externally via regenerate-proto.sh using scalapbc CLI
      libraryDependencies ++= Seq(
        "com.thesamet.scalapb" %% "scalapb-runtime" % "0.11.20",
      )
    )

lazy val hermes =
  Common
    .jvmProject("a8-hermes", file("hermes"), "hermes")
    .dependsOn(shared, nats, hermesProto)
    .settings(
      // Disable strict equality for protobuf generated code and enum types
      scalacOptions := scalacOptions.value.filterNot(_ == "-language:strictEquality"),
      // The wsconform harness drives WsConformClientMain over stdin/stdout, and sbt does not
      // forward stdin to a forked run (connectInput has no effect in -batch). So the harness
      // never launches sbt: it calls this task ONCE to materialize the classpath, then execs
      // `java -cp @<file>` per scenario. That also drops the sbt+JVM boot cost from every one
      // of them, and keeps sbt off the stream that carries the protocol.
      wsconformClasspath := {
        val file = target.value / "wsconform-classpath.txt"
        IO.write(file, (Compile / fullClasspath).value.files.mkString(":"))
        file
      },
      libraryDependencies ++= Seq(
        "org.bouncycastle" % "bcprov-jdk18on" % "1.77",
        "com.hierynomus" % "sshj" % "0.38.0",
        // scalapb JSON (protojson) so RPC handlers can decode/encode by the request's contentType —
        // a JSON-speaking client (e.g. the browser ws/send_receive_json path) is handled natively
        // instead of every typed handler being hardwired to binary protobuf.
        "com.thesamet.scalapb" %% "scalapb-json4s" % "0.12.1",
        "org.scalatest" %% "scalatest" % "3.2.15" % "test",
      )
    )


lazy val shared =
  Common
    .jvmProject("a8-sync-shared", file("shared"), "shared")
    .dependsOn(logging_logback)
//    .crossProject("a8-sync-shared", file("shared"), "shared")
    .settings(
//      testFrameworks += new TestFramework("zio.test.sbt.ZTestFramework"),
      Compile / unmanagedSourceDirectories :=
        Seq(
          baseDirectory.value / "jvm" / "src" / "main" / "scala",
          baseDirectory.value / "shared" / "src" / "main" / "scala",
        ),
      Compile / unmanagedResourceDirectories :=
        Seq(
          baseDirectory.value / "jvm" / "src" / "main" / "resources",
          baseDirectory.value / "shared" / "src" / "main" / "resources",
        ),
      Test / unmanagedResourceDirectories :=
        Seq(
          baseDirectory.value / "jvm" / "src" / "test" / "resources",
          baseDirectory.value / "shared" / "src" / "test" / "resources",
        ),
      Test / unmanagedSourceDirectories :=
        Seq(
          baseDirectory.value / "jvm" / "src" / "test" / "scala",
          baseDirectory.value / "shared" / "src" / "test" / "scala",
        ),
      libraryDependencies ++= Seq(
//        zeroWastePlugin,
        "com.softwaremill.ox" %% "core" % "0.7.0",
        "org.typelevel" %% "case-insensitive" % "1.3.0",
        "com.beachape" %%% "enumeratum" % "1.7.2",
        "com.lihaoyi" %%% "sourcecode" % "0.3.0",
        "com.softwaremill.sttp.client4" %% "core" % "4.0.9",
        "org.scalactic" %% "scalactic" % "3.2.15" % "test",
        "org.scalatest" %% "scalatest" % "3.2.15" % "test",
        "org.typelevel" %% "jawn-parser" % "1.4.0",
        "org.typelevel" %% "jawn-ast" % "1.4.0",
//        "dev.zio" %%% "zio-prelude" % "1.0.0-RC16",
//        "dev.zio" %%% "zio-streams" % zioVersion,
//        "dev.zio" %%% "zio-test" % zioVersion % Test,
//        "dev.zio" %%% "zio-test-sbt" % zioVersion % Test,
//        "dev.zio" %%% "zio-test-magnolia" % zioVersion % Test,
//      )
//    )
//    .jvmSettings(
//      libraryDependencies ++= Seq(
//        "com.softwaremill.sttp.client3" %% "zio" % "3.8.11",
        "org.hsqldb" % "hsqldb" % "2.7.1",
//        "dev.zio" %% "zio-cache" % "0.2.2",
        "com.github.andyglow" %% "typesafe-config-scala" % "2.0.0",
        "org.postgresql" % "postgresql" % "42.5.3",
        "mysql" % "mysql-connector-java" % "8.0.32",
        "net.sf.jt400" % "jt400" % "11.1",
        "com.zaxxer" % "HikariCP" % "5.0.1",
        "com.sun.mail" % "jakarta.mail" % "2.0.1",
      )
    )
//    .jsSettings(
//      libraryDependencies ++= Seq(
//        "org.scala-js" %%% "scalajs-dom" % "2.2.0",
//      )
//    )

//lazy val sharedJVM = shared.jvm
//lazy val sharedJS = shared.js


lazy val hermesTest =
  Common
    .jvmProject("hermes-test", file("examples/hermes-test"), "hermesTest")
    .dependsOn(hermes)
    .settings(
      publish := {},
      libraryDependencies ++= Seq(
      )
    )

//lazy val sharedJVM = shared.jvm
//lazy val sharedJS = shared.js


lazy val root =
  Common.jvmProject("root", file("target/root"), id = "root")
    .settings( publish := {} )
    .settings( com.jsuereth.sbtpgp.PgpKeys.publishSigned := {} )
//    .aggregate(api)
//    .aggregate(http)
    .aggregate(nats)
    .aggregate(hermesProto)
    .aggregate(hermes)
    .aggregate(shared)
    .aggregate(loggingJVM)
//    .aggregate(loggingJS)
    .aggregate(logging_logback)
    .aggregate(logging_logback_test)



   
