// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.continuum.continuum_rpc

/** @param reason
  *   human-readable denial reason when !allowed
  */
@SerialVersionUID(0L)
final case class AuthorizeForJobResponse(
    allowed: _root_.scala.Boolean = false,
    reason: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[AuthorizeForJobResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = allowed
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(1, __value)
        }
      };
      
      {
        val __value = reason
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = allowed
        if (__v != false) {
          _output__.writeBool(1, __v)
        }
      };
      {
        val __v = reason
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withAllowed(__v: _root_.scala.Boolean): AuthorizeForJobResponse = copy(allowed = __v)
    def withReason(__v: _root_.scala.Predef.String): AuthorizeForJobResponse = copy(reason = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = allowed
          if (__t != false) __t else null
        }
        case 2 => {
          val __t = reason
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PBoolean(allowed)
        case 2 => _root_.scalapb.descriptors.PString(reason)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse.type = a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse
    // @@protoc_insertion_point(GeneratedMessage[continuum_rpc.AuthorizeForJobResponse])
}

object AuthorizeForJobResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse = {
    var __allowed: _root_.scala.Boolean = false
    var __reason: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __allowed = _input__.readBool()
        case 18 =>
          __reason = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse(
        allowed = __allowed,
        reason = __reason,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse(
        allowed = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        reason = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ContinuumRpcProto.javaDescriptor.getMessageTypes().get(24)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ContinuumRpcProto.scalaDescriptor.messages(24)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse(
    allowed = false,
    reason = ""
  )
  implicit class AuthorizeForJobResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse](_l) {
    def allowed: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.allowed)((c_, f_) => c_.copy(allowed = f_))
    def reason: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.reason)((c_, f_) => c_.copy(reason = f_))
  }
  final val ALLOWED_FIELD_NUMBER = 1
  final val REASON_FIELD_NUMBER = 2
  def of(
    allowed: _root_.scala.Boolean,
    reason: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse = _root_.a8.hermes.proto.continuum.continuum_rpc.AuthorizeForJobResponse(
    allowed,
    reason
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[continuum_rpc.AuthorizeForJobResponse])
}
