// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.continuum.continuum_rpc

/** LogError is a logged error, with its chain intact. The `cause` link is what
  * makes it worth being a message rather than a string: a wrapped error (Go's
  * stacktrace.Propagate / fmt.Errorf %w, the JVM's getCause) is a CHAIN, and the
  * root cause — the interesting one — is at the far end of it. Flattening it to
  * text is what forces a human to read a wall of prose to find the bottom frame.
  *
  * @param message
  *   message is this link's own message (err.Error() / Throwable.getMessage()).
  * @param type
  *   type is the concrete error/exception type ("*net.OpError",
  *   "java.io.IOException"). A FIELD, so "show me every IOException in the fleet"
  *   is a filter rather than a substring guess.
  * @param stack
  *   stack is the rendered stack trace / propagation frames for this link.
  * @param cause
  *   cause is the wrapped error, recursively. Nil at the root.
  */
@SerialVersionUID(0L)
final case class LogError(
    message: _root_.scala.Predef.String = "",
    `type`: _root_.scala.Predef.String = "",
    stack: _root_.scala.Predef.String = "",
    cause: _root_.scala.Option[a8.hermes.proto.continuum.continuum_rpc.LogError] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[LogError] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = `type`
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = stack
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      if (cause.isDefined) {
        val __value = cause.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = `type`
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = stack
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      cause.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withMessage(__v: _root_.scala.Predef.String): LogError = copy(message = __v)
    def withType(__v: _root_.scala.Predef.String): LogError = copy(`type` = __v)
    def withStack(__v: _root_.scala.Predef.String): LogError = copy(stack = __v)
    def getCause: a8.hermes.proto.continuum.continuum_rpc.LogError = cause.getOrElse(a8.hermes.proto.continuum.continuum_rpc.LogError.defaultInstance)
    def clearCause: LogError = copy(cause = _root_.scala.None)
    def withCause(__v: a8.hermes.proto.continuum.continuum_rpc.LogError): LogError = copy(cause = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = `type`
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = stack
          if (__t != "") __t else null
        }
        case 4 => cause.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(message)
        case 2 => _root_.scalapb.descriptors.PString(`type`)
        case 3 => _root_.scalapb.descriptors.PString(stack)
        case 4 => cause.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.continuum.continuum_rpc.LogError.type = a8.hermes.proto.continuum.continuum_rpc.LogError
    // @@protoc_insertion_point(GeneratedMessage[continuum_rpc.LogError])
}

object LogError extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.continuum.continuum_rpc.LogError] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.continuum.continuum_rpc.LogError] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.continuum.continuum_rpc.LogError = {
    var __message: _root_.scala.Predef.String = ""
    var __type: _root_.scala.Predef.String = ""
    var __stack: _root_.scala.Predef.String = ""
    var __cause: _root_.scala.Option[a8.hermes.proto.continuum.continuum_rpc.LogError] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __message = _input__.readStringRequireUtf8()
        case 18 =>
          __type = _input__.readStringRequireUtf8()
        case 26 =>
          __stack = _input__.readStringRequireUtf8()
        case 34 =>
          __cause = _root_.scala.Option(__cause.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.continuum.continuum_rpc.LogError](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.continuum.continuum_rpc.LogError(
        message = __message,
        `type` = __type,
        stack = __stack,
        cause = __cause,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.continuum.continuum_rpc.LogError] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.continuum.continuum_rpc.LogError(
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        `type` = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        stack = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        cause = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.continuum.continuum_rpc.LogError]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ContinuumRpcProto.javaDescriptor.getMessageTypes().get(16)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ContinuumRpcProto.scalaDescriptor.messages(16)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = a8.hermes.proto.continuum.continuum_rpc.LogError
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.continuum.continuum_rpc.LogError(
    message = "",
    `type` = "",
    stack = "",
    cause = _root_.scala.None
  )
  implicit class LogErrorLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.continuum.continuum_rpc.LogError]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.continuum.continuum_rpc.LogError](_l) {
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
    def stack: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.stack)((c_, f_) => c_.copy(stack = f_))
    def cause: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.continuum.continuum_rpc.LogError] = field(_.getCause)((c_, f_) => c_.copy(cause = _root_.scala.Option(f_)))
    def optionalCause: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.continuum.continuum_rpc.LogError]] = field(_.cause)((c_, f_) => c_.copy(cause = f_))
  }
  final val MESSAGE_FIELD_NUMBER = 1
  final val TYPE_FIELD_NUMBER = 2
  final val STACK_FIELD_NUMBER = 3
  final val CAUSE_FIELD_NUMBER = 4
  def of(
    message: _root_.scala.Predef.String,
    `type`: _root_.scala.Predef.String,
    stack: _root_.scala.Predef.String,
    cause: _root_.scala.Option[a8.hermes.proto.continuum.continuum_rpc.LogError]
  ): _root_.a8.hermes.proto.continuum.continuum_rpc.LogError = _root_.a8.hermes.proto.continuum.continuum_rpc.LogError(
    message,
    `type`,
    stack,
    cause
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[continuum_rpc.LogError])
}
