// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.continuum.continuum_rpc

/** LogLevel mirrors log/log.go's five levels. Deliberately NOT the LogLevel in
  * pkg/rpc/process/process_rpc.proto: that one is unused, lacks trace, and importing
  * it would couple continuum_rpc to process_rpc for nothing.
  */
sealed abstract class LogLevel(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = a8.hermes.proto.continuum.continuum_rpc.LogLevel
  type RecognizedType = a8.hermes.proto.continuum.continuum_rpc.LogLevel.Recognized
  def islevelunspecified: _root_.scala.Boolean = false
  def istrace: _root_.scala.Boolean = false
  def isdebug: _root_.scala.Boolean = false
  def isinfo: _root_.scala.Boolean = false
  def iswarn: _root_.scala.Boolean = false
  def iserror: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[LogLevel] = a8.hermes.proto.continuum.continuum_rpc.LogLevel
  final def asRecognized: _root_.scala.Option[a8.hermes.proto.continuum.continuum_rpc.LogLevel.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[a8.hermes.proto.continuum.continuum_rpc.LogLevel.Recognized])
}

object LogLevel extends _root_.scalapb.GeneratedEnumCompanion[LogLevel] {
  sealed trait Recognized extends LogLevel
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[LogLevel] = this
  
  @SerialVersionUID(0L)
  case object level_unspecified extends LogLevel(0) with LogLevel.Recognized {
    val index = 0
    val name = "level_unspecified"
    override def islevelunspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object trace extends LogLevel(1) with LogLevel.Recognized {
    val index = 1
    val name = "trace"
    override def istrace: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object debug extends LogLevel(2) with LogLevel.Recognized {
    val index = 2
    val name = "debug"
    override def isdebug: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object info extends LogLevel(3) with LogLevel.Recognized {
    val index = 3
    val name = "info"
    override def isinfo: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object warn extends LogLevel(4) with LogLevel.Recognized {
    val index = 4
    val name = "warn"
    override def iswarn: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object error extends LogLevel(5) with LogLevel.Recognized {
    val index = 5
    val name = "error"
    override def iserror: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends LogLevel(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(level_unspecified, trace, debug, info, warn, error)
  def fromValue(__value: _root_.scala.Int): LogLevel = __value match {
    case 0 => level_unspecified
    case 1 => trace
    case 2 => debug
    case 3 => info
    case 4 => warn
    case 5 => error
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = ContinuumRpcProto.javaDescriptor.getEnumTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = ContinuumRpcProto.scalaDescriptor.enums(1)
}