pages = [{"l":"index.html#","e":false,"i":"","n":"a8-logging","t":"a8-logging","d":"","k":"static","x":""},
{"l":"a8/common/logging.html#","e":false,"i":"","n":"a8.common.logging","t":"a8.common.logging","d":"","k":"package","x":""},
{"l":"a8/common/logging/println.html#","e":false,"i":"","n":"a8.common.logging.println","t":"a8.common.logging.println","d":"","k":"package","x":""},
{"l":"a8/common/logging/println/PrintlnLogger$.html#","e":false,"i":"","n":"PrintlnLogger","t":"PrintlnLogger","d":"a8.common.logging.println","k":"object","x":""},
{"l":"a8/common/logging/println/PrintlnLogger$.html#globalLevel-0","e":false,"i":"","n":"globalLevel","t":"globalLevel: Level","d":"a8.common.logging.println.PrintlnLogger","k":"var","x":""},
{"l":"a8/common/logging/println/PrintlnLogger$.html#loggingLevel-0","e":false,"i":"","n":"loggingLevel","t":"loggingLevel: Level","d":"a8.common.logging.println.PrintlnLogger","k":"var","x":""},
{"l":"a8/common/logging/println/PrintlnLogger$.html#sdf-0","e":false,"i":"","n":"sdf","t":"sdf: SimpleDateFormat","d":"a8.common.logging.println.PrintlnLogger","k":"val","x":""},
{"l":"a8/common/logging/println/PrintlnLogger.html#","e":false,"i":"","n":"PrintlnLogger","t":"PrintlnLogger(val name: String) extends Logger","d":"a8.common.logging.println","k":"class","x":""},
{"l":"a8/common/logging/println/PrintlnLogger.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"a8.common.logging.println.PrintlnLogger","k":"val","x":""},
{"l":"a8/common/logging/println/PrintlnLoggerFactory$.html#","e":false,"i":"","n":"PrintlnLoggerFactory","t":"PrintlnLoggerFactory extends LoggerFactory","d":"a8.common.logging.println","k":"object","x":""},
{"l":"a8/common/logging/JsonApi$.html#","e":false,"i":"","n":"JsonApi","t":"JsonApi","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/JsonApi$.html#apply-dd1","e":false,"i":"","n":"apply","t":"apply[A : JsonApi]: JsonApi[A]","d":"a8.common.logging.JsonApi","k":"def","x":""},
{"l":"a8/common/logging/JsonApi.html#","e":false,"i":"","n":"JsonApi","t":"JsonApi[A]","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/JsonApi.html#toJsonStr-9f8","e":false,"i":"","n":"toJsonStr","t":"toJsonStr(a: A): String","d":"a8.common.logging.JsonApi","k":"def","x":""},
{"l":"a8/common/logging/Level$.html#","e":false,"i":"","n":"Level","t":"Level","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/Level$.html#given_CanEqual_Level_Level-0","e":false,"i":"","n":"given_CanEqual_Level_Level","t":"given_CanEqual_Level_Level: CanEqual[Level, Level]","d":"a8.common.logging.Level","k":"given","x":""},
{"l":"a8/common/logging/Level$.html#valuesByLc-0","e":false,"i":"","n":"valuesByLc","t":"valuesByLc: Map[String, Level]","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#","e":false,"i":"","n":"Level","t":"Level extends Ordered[Level]","d":"a8.common.logging","k":"enum","x":""},
{"l":"a8/common/logging/Level.html#All-0","e":false,"i":"","n":"All","t":"All extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Trace-0","e":false,"i":"","n":"Trace","t":"Trace extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Debug-0","e":false,"i":"","n":"Debug","t":"Debug extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Info-0","e":false,"i":"","n":"Info","t":"Info extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Warn-0","e":false,"i":"","n":"Warn","t":"Warn extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Error-0","e":false,"i":"","n":"Error","t":"Error extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Fatal-0","e":false,"i":"","n":"Fatal","t":"Fatal extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/Level.html#Off-0","e":false,"i":"","n":"Off","t":"Off extends Level","d":"a8.common.logging.Level","k":"val","x":""},
{"l":"a8/common/logging/LogMessage$.html#","e":false,"i":"","n":"LogMessage","t":"LogMessage","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LogMessage$.html#apply-fffff703","e":false,"i":"","n":"apply","t":"apply(message: String)(implicit trace: Trace): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$.html#create-588","e":false,"i":"","n":"create","t":"create(implicit trace: Trace): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$.html#","e":false,"i":"","n":"impl","t":"impl","d":"a8.common.logging.LogMessage","k":"object","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#","e":false,"i":"","n":"LogMessageInternal","t":"LogMessageInternal(parts: List[LogPart]) extends LogMessage","d":"a8.common.logging.LogMessage.impl","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#consoleMessage-fffff0c3","e":false,"i":"","n":"consoleMessage","t":"consoleMessage(message: String): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#consoleValue-2f1","e":false,"i":"","n":"consoleValue","t":"consoleValue(value: Any): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#exception-c4a","e":false,"i":"","n":"exception","t":"exception(th: Throwable): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#expr-fffffb80","e":false,"i":"","n":"expr","t":"expr[A](value: Text[A]): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#jsonConsoleValue-51","e":false,"i":"","n":"jsonConsoleValue","t":"jsonConsoleValue[A : JsonApi](value: A): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#message-fffff0c3","e":false,"i":"","n":"message","t":"message(value: String): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#resolve-0","e":false,"i":"","n":"resolve","t":"resolve: ResolvedLogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogMessageInternal.html#throwable-c4a","e":false,"i":"","n":"throwable","t":"throwable(th: Throwable): LogMessage","d":"a8.common.logging.LogMessage.impl.LogMessageInternal","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$.html#","e":false,"i":"","n":"LogPart","t":"LogPart","d":"a8.common.logging.LogMessage.impl","k":"object","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$ConsoleMessage.html#","e":false,"i":"","n":"ConsoleMessage","t":"ConsoleMessage(value: String) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$ConsoleValue.html#","e":false,"i":"","n":"ConsoleValue","t":"ConsoleValue(value: Any) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$Expr.html#","e":false,"i":"","n":"Expr","t":"Expr[A](value: Text[A]) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$Expr.html#asString-0","e":false,"i":"","n":"asString","t":"asString: String","d":"a8.common.logging.LogMessage.impl.LogPart.Expr","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$JsonConsoleValue.html#","e":false,"i":"","n":"JsonConsoleValue","t":"JsonConsoleValue[A](value: A)(using evidence$1: JsonApi[A]) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$JsonConsoleValue.html#asJsonStr-0","e":false,"i":"","n":"asJsonStr","t":"asJsonStr: String","d":"a8.common.logging.LogMessage.impl.LogPart.JsonConsoleValue","k":"def","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$Message.html#","e":false,"i":"","n":"Message","t":"Message(value: String) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$Throw.html#","e":false,"i":"","n":"Throw","t":"Throw(th: Throwable) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart$$TracePart.html#","e":false,"i":"","n":"TracePart","t":"TracePart(trace: Trace) extends LogPart","d":"a8.common.logging.LogMessage.impl.LogPart","k":"class","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$LogPart.html#","e":false,"i":"","n":"LogPart","t":"LogPart","d":"a8.common.logging.LogMessage.impl","k":"trait","x":""},
{"l":"a8/common/logging/LogMessage$$impl$$ResolvedLogMessage.html#","e":false,"i":"","n":"ResolvedLogMessage","t":"ResolvedLogMessage(consoleMessage: Option[String], message: String, throwable: Option[Throwable], consoleValues: Seq[Any])","d":"a8.common.logging.LogMessage.impl","k":"class","x":""},
{"l":"a8/common/logging/LogMessage.html#","e":false,"i":"","n":"LogMessage","t":"LogMessage","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/LogMessage.html#consoleMessage-fffff0c3","e":false,"i":"","n":"consoleMessage","t":"consoleMessage(message: String): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#consoleValue-2f1","e":false,"i":"","n":"consoleValue","t":"consoleValue(value: Any): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#exception-c4a","e":false,"i":"","n":"exception","t":"exception(th: Throwable): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#expr-fffffb80","e":false,"i":"","n":"expr","t":"expr[A](value: Text[A]): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#jsonConsoleValue-51","e":false,"i":"","n":"jsonConsoleValue","t":"jsonConsoleValue[A : JsonApi](value: A): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#message-fffff0c3","e":false,"i":"","n":"message","t":"message(value: String): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#resolve-0","e":false,"i":"","n":"resolve","t":"resolve: ResolvedLogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/LogMessage.html#throwable-c4a","e":false,"i":"","n":"throwable","t":"throwable(th: Throwable): LogMessage","d":"a8.common.logging.LogMessage","k":"def","x":""},
{"l":"a8/common/logging/Logger$.html#","e":false,"i":"","n":"Logger","t":"Logger","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/Logger$.html#logger-fffff575","e":false,"i":"","n":"logger","t":"logger(implicit trace: Trace): Logger","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger$.html#logger-b6f","e":false,"i":"","n":"logger","t":"logger(clazz: Class[_]): Logger","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger$.html#logger-630","e":false,"i":"","n":"logger","t":"logger(name: String): Logger","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger$.html#of-f17","e":false,"i":"","n":"of","t":"of[A : ClassTag]: Logger","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#","e":false,"i":"","n":"Logger","t":"Logger","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/Logger.html#debug-bb1","e":false,"i":"","n":"debug","t":"debug(msg: String)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#debug-fffffa6f","e":false,"i":"","n":"debug","t":"debug(msg: String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#debug-fffffc8a","e":false,"i":"","n":"debug","t":"debug(th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#debug-fffff158","e":false,"i":"","n":"debug","t":"debug(msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#debug-fffff91a","e":false,"i":"","n":"debug","t":"debug(msg: () => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#error-bb1","e":false,"i":"","n":"error","t":"error(msg: String)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#error-fffffa6f","e":false,"i":"","n":"error","t":"error(msg: String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#error-fffffc8a","e":false,"i":"","n":"error","t":"error(th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#error-fffff158","e":false,"i":"","n":"error","t":"error(msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#error-fffff91a","e":false,"i":"","n":"error","t":"error(msg: () => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#fatal-bb1","e":false,"i":"","n":"fatal","t":"fatal(msg: String)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#fatal-fffffa6f","e":false,"i":"","n":"fatal","t":"fatal(msg: String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#fatal-fffffc8a","e":false,"i":"","n":"fatal","t":"fatal(th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#fatal-fffff158","e":false,"i":"","n":"fatal","t":"fatal(msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#fatal-fffff91a","e":false,"i":"","n":"fatal","t":"fatal(msg: () => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#info-bb1","e":false,"i":"","n":"info","t":"info(msg: String)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#info-fffffa6f","e":false,"i":"","n":"info","t":"info(msg: String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#info-fffffc8a","e":false,"i":"","n":"info","t":"info(th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#info-fffff158","e":false,"i":"","n":"info","t":"info(msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#info-fffff91a","e":false,"i":"","n":"info","t":"info(msg: () => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isDebugEnabled-0","e":false,"i":"","n":"isDebugEnabled","t":"isDebugEnabled: Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isErrorEnabled-0","e":false,"i":"","n":"isErrorEnabled","t":"isErrorEnabled: Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isFatalEnabled-0","e":false,"i":"","n":"isFatalEnabled","t":"isFatalEnabled: Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isInfoEnabled-0","e":false,"i":"","n":"isInfoEnabled","t":"isInfoEnabled: Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isLevelEnabled-fffffb17","e":false,"i":"","n":"isLevelEnabled","t":"isLevelEnabled(level: Level): Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isTraceEnabled-0","e":false,"i":"","n":"isTraceEnabled","t":"isTraceEnabled: Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#isWarnEnabled-0","e":false,"i":"","n":"isWarnEnabled","t":"isWarnEnabled: Boolean","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#lazyLog-d91","e":false,"i":"","n":"lazyLog","t":"lazyLog(level: Level, msg: => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#lazyLog-7cf","e":false,"i":"","n":"lazyLog","t":"lazyLog(level: Level, msg: => LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#log-94","e":false,"i":"","n":"log","t":"log(msg: String, th: Option[Throwable])(using Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#log-fffff4d8","e":false,"i":"","n":"log","t":"log(level: Level, msg: String, th: Throwable)(using Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#log-b0f","e":false,"i":"","n":"log","t":"log(level: Level, msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#setLevel-fffff8f5","e":false,"i":"","n":"setLevel","t":"setLevel(l: Level): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#trace-bb1","e":false,"i":"","n":"trace","t":"trace(msg: String)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#trace-fffffa6f","e":false,"i":"","n":"trace","t":"trace(msg: String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#trace-fffffc8a","e":false,"i":"","n":"trace","t":"trace(th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#trace-fffff158","e":false,"i":"","n":"trace","t":"trace(msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#trace-fffff91a","e":false,"i":"","n":"trace","t":"trace(msg: () => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#warn-bb1","e":false,"i":"","n":"warn","t":"warn(msg: String)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#warn-fffffa6f","e":false,"i":"","n":"warn","t":"warn(msg: String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#warn-fffffc8a","e":false,"i":"","n":"warn","t":"warn(th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#warn-fffff158","e":false,"i":"","n":"warn","t":"warn(msg: LogMessage)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/Logger.html#warn-fffff91a","e":false,"i":"","n":"warn","t":"warn(msg: () => String, th: Throwable)(implicit trace: Trace): Unit","d":"a8.common.logging.Logger","k":"def","x":""},
{"l":"a8/common/logging/LoggerFactory$.html#","e":false,"i":"","n":"LoggerFactory","t":"LoggerFactory extends LoggerFactory, LoggerFactoryCompanionImpl","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LoggerFactory.html#","e":false,"i":"","n":"LoggerFactory","t":"LoggerFactory","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/LoggerFactory.html#logger-630","e":false,"i":"","n":"logger","t":"logger(name: String): Logger","d":"a8.common.logging.LoggerFactory","k":"def","x":""},
{"l":"a8/common/logging/LoggerFactory.html#withContext-6cd","e":false,"i":"","n":"withContext","t":"withContext[A](context: String)(fn: => A): A","d":"a8.common.logging.LoggerFactory","k":"def","x":""},
{"l":"a8/common/logging/LoggerFactoryCompanionImpl.html#","e":false,"i":"","n":"LoggerFactoryCompanionImpl","t":"LoggerFactoryCompanionImpl","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/LoggerFactoryCompanionImpl.html#instantiateLoggerFactory-fbf","e":false,"i":"","n":"instantiateLoggerFactory","t":"instantiateLoggerFactory(): LoggerFactory","d":"a8.common.logging.LoggerFactoryCompanionImpl","k":"def","x":""},
{"l":"a8/common/logging/LoggerFactoryServiceLoader$.html#","e":false,"i":"","n":"LoggerFactoryServiceLoader","t":"LoggerFactoryServiceLoader","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LoggerFactoryServiceLoader$.html#loadLoggerFactory-fbf","e":false,"i":"","n":"loadLoggerFactory","t":"loadLoggerFactory(): LoggerFactory","d":"a8.common.logging.LoggerFactoryServiceLoader","k":"def","x":""},
{"l":"a8/common/logging/LoggerFactoryServiceLoader.html#","e":false,"i":"","n":"LoggerFactoryServiceLoader","t":"LoggerFactoryServiceLoader","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/LoggerFactoryServiceLoader.html#loggerFactory-0","e":false,"i":"","n":"loggerFactory","t":"loggerFactory: LoggerFactory","d":"a8.common.logging.LoggerFactoryServiceLoader","k":"def","x":""},
{"l":"a8/common/logging/LoggerFactoryServiceLoader.html#priority-0","e":false,"i":"","n":"priority","t":"priority: Int","d":"a8.common.logging.LoggerFactoryServiceLoader","k":"def","x":""},
{"l":"a8/common/logging/Logging$.html#","e":false,"i":"","n":"Logging","t":"Logging","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/Logging$.html#logger-fffff575","e":false,"i":"","n":"logger","t":"logger(implicit trace: Trace): Logger","d":"a8.common.logging.Logging","k":"def","x":""},
{"l":"a8/common/logging/Logging$.html#logger-b6f","e":false,"i":"","n":"logger","t":"logger(clazz: Class[_]): Logger","d":"a8.common.logging.Logging","k":"def","x":""},
{"l":"a8/common/logging/Logging.html#","e":false,"i":"","n":"Logging","t":"Logging","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$.html#","e":false,"i":"","n":"LoggingBootstrapConfig","t":"LoggingBootstrapConfig","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$.html#defaultHasColorConsole-0","e":false,"i":"","n":"defaultHasColorConsole","t":"defaultHasColorConsole: Boolean","d":"a8.common.logging.LoggingBootstrapConfig","k":"val","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$.html#fileFromProperty-fffff962","e":false,"i":"","n":"fileFromProperty","t":"fileFromProperty(propertyName: String, default: String): File","d":"a8.common.logging.LoggingBootstrapConfig","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$.html#finalizeConfig-e00","e":false,"i":"","n":"finalizeConfig","t":"finalizeConfig(bootstrapConfig: LoggingBootstrapConfig, applySystemPropertyOverrides: Boolean): Unit","d":"a8.common.logging.LoggingBootstrapConfig","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$.html#finalizedConfig-0","e":false,"i":"","n":"finalizedConfig","t":"finalizedConfig: LoggingBootstrapConfig","d":"a8.common.logging.LoggingBootstrapConfig","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$.html#insideOfIntellij-0","e":false,"i":"","n":"insideOfIntellij","t":"insideOfIntellij: Boolean","d":"a8.common.logging.LoggingBootstrapConfig","k":"val","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$$LoggingBootstrapConfigDto.html#","e":false,"i":"","n":"LoggingBootstrapConfigDto","t":"LoggingBootstrapConfigDto(overrideSystemErr: Option[Boolean], overrideSystemOut: Option[Boolean], setDefaultUncaughtExceptionHandler: Option[Boolean], fileLogging: Option[Boolean], consoleLogging: Option[Boolean], hasColorConsole: Option[Boolean], defaultLogLevel: Option[String])","d":"a8.common.logging.LoggingBootstrapConfig","k":"class","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$$LoggingBootstrapConfigDto.html#+-900","e":false,"i":"","n":"+","t":"+(right: LoggingBootstrapConfigDto): LoggingBootstrapConfigDto","d":"a8.common.logging.LoggingBootstrapConfig.LoggingBootstrapConfigDto","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$$LoggingBootstrapConfigDto.html#asLoggingBootstrapConfig-fffffec1","e":false,"i":"","n":"asLoggingBootstrapConfig","t":"asLoggingBootstrapConfig(appName: String, configDirectory: File, logsDirectory: File): LoggingBootstrapConfig","d":"a8.common.logging.LoggingBootstrapConfig.LoggingBootstrapConfigDto","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$$LoggingBootstrapConfigDto$.html#","e":false,"i":"","n":"LoggingBootstrapConfigDto","t":"LoggingBootstrapConfigDto","d":"a8.common.logging.LoggingBootstrapConfig","k":"object","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig$$LoggingBootstrapConfigDto$.html#default-0","e":false,"i":"","n":"default","t":"default: LoggingBootstrapConfigDto","d":"a8.common.logging.LoggingBootstrapConfig.LoggingBootstrapConfigDto","k":"val","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig.html#","e":false,"i":"","n":"LoggingBootstrapConfig","t":"LoggingBootstrapConfig(overrideSystemErr: Boolean, overrideSystemOut: Boolean, setDefaultUncaughtExceptionHandler: Boolean, fileLogging: Boolean, consoleLogging: Boolean, hasColorConsole: Boolean, appName: String, configDirectory: File, logsDirectory: File, defaultLogLevel: Level)","d":"a8.common.logging","k":"class","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig.html#archivesDirectory-0","e":false,"i":"","n":"archivesDirectory","t":"archivesDirectory: File","d":"a8.common.logging.LoggingBootstrapConfig","k":"val","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig.html#asProperties-acd","e":false,"i":"","n":"asProperties","t":"asProperties(prefix: String): Map[String, String]","d":"a8.common.logging.LoggingBootstrapConfig","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfig.html#overrideWith-fffff3be","e":false,"i":"","n":"overrideWith","t":"overrideWith(propFn: (String, Boolean) => Boolean): LoggingBootstrapConfig","d":"a8.common.logging.LoggingBootstrapConfig","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfigServiceLoader$.html#","e":false,"i":"","n":"LoggingBootstrapConfigServiceLoader","t":"LoggingBootstrapConfigServiceLoader","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfigServiceLoader$.html#loggingBootstrapConfig-0","e":false,"i":"","n":"loggingBootstrapConfig","t":"loggingBootstrapConfig: LoggingBootstrapConfig","d":"a8.common.logging.LoggingBootstrapConfigServiceLoader","k":"val","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfigServiceLoader.html#","e":false,"i":"","n":"LoggingBootstrapConfigServiceLoader","t":"LoggingBootstrapConfigServiceLoader","d":"a8.common.logging","k":"class","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfigServiceLoader.html#loggingBootstrapConfig-0","e":false,"i":"","n":"loggingBootstrapConfig","t":"loggingBootstrapConfig: LoggingBootstrapConfig","d":"a8.common.logging.LoggingBootstrapConfigServiceLoader","k":"def","x":""},
{"l":"a8/common/logging/LoggingBootstrapConfigServiceLoader.html#priority-0","e":false,"i":"","n":"priority","t":"priority: Int","d":"a8.common.logging.LoggingBootstrapConfigServiceLoader","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#","e":false,"i":"","n":"LoggingOps","t":"LoggingOps","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LoggingOps$.html#LoggingThrowableOps-fffff080","e":false,"i":"","n":"LoggingThrowableOps","t":"LoggingThrowableOps(_value: Throwable): LoggingThrowableOps","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#PathOps-fffff8e4","e":false,"i":"","n":"PathOps","t":"PathOps(path: Path): PathOps","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#StringOps-fffff2ca","e":false,"i":"","n":"StringOps","t":"StringOps(source: String): StringOps","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#fileExtension-bfd","e":false,"i":"","n":"fileExtension","t":"fileExtension(file: File): String","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#normalizeClassname-fffff2ca","e":false,"i":"","n":"normalizeClassname","t":"normalizeClassname(classname: String): String","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#normalizeClassname-709","e":false,"i":"","n":"normalizeClassname","t":"normalizeClassname(clazz: Class[_]): String","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$.html#readFile-bfd","e":false,"i":"","n":"readFile","t":"readFile(file: File): String","d":"a8.common.logging.LoggingOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$LoggingThrowableOps.html#","e":false,"i":"","n":"LoggingThrowableOps","t":"LoggingThrowableOps(_value: Throwable) extends AnyVal","d":"a8.common.logging.LoggingOps","k":"class","x":""},
{"l":"a8/common/logging/LoggingOps$$LoggingThrowableOps.html#allCauses-0","e":false,"i":"","n":"allCauses","t":"allCauses: Vector[Throwable]","d":"a8.common.logging.LoggingOps.LoggingThrowableOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$LoggingThrowableOps.html#rootCause-0","e":false,"i":"","n":"rootCause","t":"rootCause: Throwable","d":"a8.common.logging.LoggingOps.LoggingThrowableOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$LoggingThrowableOps.html#stackTraceAsString-0","e":false,"i":"","n":"stackTraceAsString","t":"stackTraceAsString: String","d":"a8.common.logging.LoggingOps.LoggingThrowableOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#","e":false,"i":"","n":"PathOps","t":"PathOps(path: Path)","d":"a8.common.logging.LoggingOps","k":"class","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#appendSuffixToName-fffff676","e":false,"i":"","n":"appendSuffixToName","t":"appendSuffixToName(suffix: String): Path","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#creationTime-0","e":false,"i":"","n":"creationTime","t":"creationTime: LocalDateTime","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#delete-94c","e":false,"i":"","n":"delete","t":"delete(): Unit","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#exists-0","e":false,"i":"","n":"exists","t":"exists: Boolean","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#isDirectory-0","e":false,"i":"","n":"isDirectory","t":"isDirectory: Boolean","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#isFile-0","e":false,"i":"","n":"isFile","t":"isFile: Boolean","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#parentOpt-0","e":false,"i":"","n":"parentOpt","t":"parentOpt: Option[Path]","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$PathOps.html#size-644","e":false,"i":"","n":"size","t":"size(): Long","d":"a8.common.logging.LoggingOps.PathOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#","e":false,"i":"","n":"StringOps","t":"StringOps(source: String) extends AnyVal","d":"a8.common.logging.LoggingOps","k":"class","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#=:=-fffffd1b","e":false,"i":"","n":"=:=","t":"=:=(right: String): Boolean","d":"a8.common.logging.LoggingOps.StringOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#indent-fffff2ca","e":false,"i":"","n":"indent","t":"indent(indent: String): String","d":"a8.common.logging.LoggingOps.StringOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#isBlankX-0","e":false,"i":"","n":"isBlankX","t":"isBlankX: Boolean","d":"a8.common.logging.LoggingOps.StringOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#isNotBlank-0","e":false,"i":"","n":"isNotBlank","t":"isNotBlank: Boolean","d":"a8.common.logging.LoggingOps.StringOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#ltrim-0","e":false,"i":"","n":"ltrim","t":"ltrim: String","d":"a8.common.logging.LoggingOps.StringOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps.html#rtrim-0","e":false,"i":"","n":"rtrim","t":"rtrim: String","d":"a8.common.logging.LoggingOps.StringOps","k":"def","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps$.html#","e":false,"i":"","n":"StringOps","t":"StringOps","d":"a8.common.logging.LoggingOps","k":"object","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps$.html#ltrimPattern-0","e":false,"i":"","n":"ltrimPattern","t":"ltrimPattern: Pattern","d":"a8.common.logging.LoggingOps.StringOps","k":"val","x":""},
{"l":"a8/common/logging/LoggingOps$$StringOps$.html#rtrimPattern-0","e":false,"i":"","n":"rtrimPattern","t":"rtrimPattern: Pattern","d":"a8.common.logging.LoggingOps.StringOps","k":"val","x":""},
{"l":"a8/common/logging/LoggingOps$$canEqual$.html#","e":false,"i":"","n":"canEqual","t":"canEqual","d":"a8.common.logging.LoggingOps","k":"object","x":""},
{"l":"a8/common/logging/LoggingOps$$canEqual$.html#given_CanEqual_A_A-fffffb7d","e":false,"i":"","n":"given_CanEqual_A_A","t":"given_CanEqual_A_A[A]: CanEqual[A, A]","d":"a8.common.logging.LoggingOps.canEqual","k":"given","x":""},
{"l":"a8/common/logging/LoggingSetupOps$.html#","e":false,"i":"","n":"LoggingSetupOps","t":"LoggingSetupOps","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/LoggingSetupOps$.html#doOneTimeSetup-fffff64b","e":false,"i":"","n":"doOneTimeSetup","t":"doOneTimeSetup(loggerFactory: LoggerFactory): Unit","d":"a8.common.logging.LoggingSetupOps","k":"def","x":""},
{"l":"a8/common/logging/PublicLogging.html#","e":false,"i":"","n":"PublicLogging","t":"PublicLogging","d":"a8.common.logging","k":"trait","x":""},
{"l":"a8/common/logging/PublicLogging.html#logger-0","e":false,"i":"","n":"logger","t":"logger: Logger","d":"a8.common.logging.PublicLogging","k":"val","x":""},
{"l":"a8/common/logging/Trace$.html#","e":false,"i":"","n":"Trace","t":"Trace","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/Trace$.html#trace-fffffc62","e":false,"i":"","n":"trace","t":"trace(using file: File, line: Line, fullName: FullName): Trace","d":"a8.common.logging.Trace","k":"given","x":""},
{"l":"a8/common/logging/Trace.html#","e":false,"i":"","n":"Trace","t":"Trace(file: File, line: Line, fullName: FullName)","d":"a8.common.logging","k":"class","x":""},
{"l":"a8/common/logging/Trace.html#loggerName-0","e":false,"i":"","n":"loggerName","t":"loggerName: String","d":"a8.common.logging.Trace","k":"def","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#","e":false,"i":"","n":"UnifiedLogLevel","t":"UnifiedLogLevel","d":"a8.common.logging","k":"object","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#All-0","e":false,"i":"","n":"All","t":"All: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Debug-0","e":false,"i":"","n":"Debug","t":"Debug: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Error-0","e":false,"i":"","n":"Error","t":"Error: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Fatal-0","e":false,"i":"","n":"Fatal","t":"Fatal: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Info-0","e":false,"i":"","n":"Info","t":"Info: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Off-0","e":false,"i":"","n":"Off","t":"Off: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Trace-0","e":false,"i":"","n":"Trace","t":"Trace: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#Warn-0","e":false,"i":"","n":"Warn","t":"Warn: UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel$.html#apply-fffff1ae","e":false,"i":"","n":"apply","t":"apply(a8LogLevel: Level): UnifiedLogLevel","d":"a8.common.logging.UnifiedLogLevel","k":"def","x":""},
{"l":"a8/common/logging/UnifiedLogLevel.html#","e":false,"i":"","n":"UnifiedLogLevel","t":"UnifiedLogLevel(a8LogLevel: Level)","d":"a8.common.logging","k":"class","x":""},
{"l":"a8/common/logging/UnifiedLogLevel.html#isTrace-0","e":false,"i":"","n":"isTrace","t":"isTrace: Boolean","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnifiedLogLevel.html#resolvedA8LogLevel-0","e":false,"i":"","n":"resolvedA8LogLevel","t":"resolvedA8LogLevel: Level","d":"a8.common.logging.UnifiedLogLevel","k":"val","x":""},
{"l":"a8/common/logging/UnitTestsLoggingBootstrapConfigServiceLoader.html#","e":false,"i":"","n":"UnitTestsLoggingBootstrapConfigServiceLoader","t":"UnitTestsLoggingBootstrapConfigServiceLoader extends LoggingBootstrapConfigServiceLoader","d":"a8.common.logging","k":"class","x":""}];