// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.process_rpc

/** @param status
  *   Overall health status
  * @param message
  *   Human-readable health information
  * @param checks
  *   Detailed health check results (if requested)
  * @param timestamp
  *   When the health check was performed
  */
@SerialVersionUID(0L)
final case class HealthCheckResponse(
    status: a8.hermes.proto.process.process_rpc.HealthStatus = a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED,
    message: _root_.scala.Predef.String = "",
    checks: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult] = _root_.scala.collection.immutable.Map.empty,
    timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[HealthCheckResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = status.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(1, __value)
        }
      };
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      checks.foreach { __item =>
        val __value = a8.hermes.proto.process.process_rpc.HealthCheckResponse._typemapper_checks.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      if (timestamp.isDefined) {
        val __value = timestamp.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = status.value
        if (__v != 0) {
          _output__.writeEnum(1, __v)
        }
      };
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      checks.foreach { __v =>
        val __m = a8.hermes.proto.process.process_rpc.HealthCheckResponse._typemapper_checks.toBase(__v)
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      timestamp.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withStatus(__v: a8.hermes.proto.process.process_rpc.HealthStatus): HealthCheckResponse = copy(status = __v)
    def withMessage(__v: _root_.scala.Predef.String): HealthCheckResponse = copy(message = __v)
    def clearChecks = copy(checks = _root_.scala.collection.immutable.Map.empty)
    def addChecks(__vs: (_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult) *): HealthCheckResponse = addAllChecks(__vs)
    def addAllChecks(__vs: Iterable[(_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult)]): HealthCheckResponse = copy(checks = checks ++ __vs)
    def withChecks(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult]): HealthCheckResponse = copy(checks = __v)
    def getTimestamp: com.google.protobuf.timestamp.Timestamp = timestamp.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearTimestamp: HealthCheckResponse = copy(timestamp = _root_.scala.None)
    def withTimestamp(__v: com.google.protobuf.timestamp.Timestamp): HealthCheckResponse = copy(timestamp = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = status.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 2 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 3 => checks.iterator.map(a8.hermes.proto.process.process_rpc.HealthCheckResponse._typemapper_checks.toBase(_)).toSeq
        case 4 => timestamp.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PEnum(status.scalaValueDescriptor)
        case 2 => _root_.scalapb.descriptors.PString(message)
        case 3 => _root_.scalapb.descriptors.PRepeated(checks.iterator.map(a8.hermes.proto.process.process_rpc.HealthCheckResponse._typemapper_checks.toBase(_).toPMessage).toVector)
        case 4 => timestamp.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.process_rpc.HealthCheckResponse.type = a8.hermes.proto.process.process_rpc.HealthCheckResponse
    // @@protoc_insertion_point(GeneratedMessage[process_rpc.HealthCheckResponse])
}

object HealthCheckResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.HealthCheckResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.HealthCheckResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.process_rpc.HealthCheckResponse = {
    var __status: a8.hermes.proto.process.process_rpc.HealthStatus = a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED
    var __message: _root_.scala.Predef.String = ""
    val __checks: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult]
    var __timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __status = a8.hermes.proto.process.process_rpc.HealthStatus.fromValue(_input__.readEnum())
        case 18 =>
          __message = _input__.readStringRequireUtf8()
        case 26 =>
          __checks += a8.hermes.proto.process.process_rpc.HealthCheckResponse._typemapper_checks.toCustom(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry](_input__))
        case 34 =>
          __timestamp = _root_.scala.Option(__timestamp.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.process_rpc.HealthCheckResponse(
        status = __status,
        message = __message,
        checks = __checks.result(),
        timestamp = __timestamp,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.process_rpc.HealthCheckResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.process_rpc.HealthCheckResponse(
        status = a8.hermes.proto.process.process_rpc.HealthStatus.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED.scalaValueDescriptor).number),
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        checks = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(a8.hermes.proto.process.process_rpc.HealthCheckResponse._typemapper_checks.toCustom(_)).toMap,
        timestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ProcessRpcProto.javaDescriptor.getMessageTypes().get(10)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ProcessRpcProto.scalaDescriptor.messages(10)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry
      case 4 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => a8.hermes.proto.process.process_rpc.HealthStatus
    }
  }
  lazy val defaultInstance = a8.hermes.proto.process.process_rpc.HealthCheckResponse(
    status = a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED,
    message = "",
    checks = _root_.scala.collection.immutable.Map.empty,
    timestamp = _root_.scala.None
  )
  @SerialVersionUID(0L)
  final case class ChecksEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Option[a8.hermes.proto.process.process_rpc.HealthCheckResult] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ChecksEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        if (value.isDefined) {
          val __value = value.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          val __m = __v
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): ChecksEntry = copy(key = __v)
      def getValue: a8.hermes.proto.process.process_rpc.HealthCheckResult = value.getOrElse(a8.hermes.proto.process.process_rpc.HealthCheckResult.defaultInstance)
      def clearValue: ChecksEntry = copy(value = _root_.scala.None)
      def withValue(__v: a8.hermes.proto.process.process_rpc.HealthCheckResult): ChecksEntry = copy(value = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry.type = a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry
      // @@protoc_insertion_point(GeneratedMessage[process_rpc.HealthCheckResponse.ChecksEntry])
  }
  
  object ChecksEntry extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Option[a8.hermes.proto.process.process_rpc.HealthCheckResult] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = _root_.scala.Option(__value.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.process_rpc.HealthCheckResult](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.process_rpc.HealthCheckResult]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = a8.hermes.proto.process.process_rpc.HealthCheckResponse.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = a8.hermes.proto.process.process_rpc.HealthCheckResponse.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = a8.hermes.proto.process.process_rpc.HealthCheckResult
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry(
      key = "",
      value = _root_.scala.None
    )
    implicit class ChecksEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResult] = field(_.getValue)((c_, f_) => c_.copy(value = _root_.scala.Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.process_rpc.HealthCheckResult]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry, (_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult)] =
      _root_.scalapb.TypeMapper[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry, (_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult)](__m => (__m.key, __m.getValue))(__p => a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry(__p._1, Some(__p._2)))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Option[a8.hermes.proto.process.process_rpc.HealthCheckResult]
    ): _root_.a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry = _root_.a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[process_rpc.HealthCheckResponse.ChecksEntry])
  }
  
  implicit class HealthCheckResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResponse](_l) {
    def status: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.HealthStatus] = field(_.status)((c_, f_) => c_.copy(status = f_))
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def checks: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult]] = field(_.checks)((c_, f_) => c_.copy(checks = f_))
    def timestamp: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getTimestamp)((c_, f_) => c_.copy(timestamp = _root_.scala.Option(f_)))
    def optionalTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
  }
  final val STATUS_FIELD_NUMBER = 1
  final val MESSAGE_FIELD_NUMBER = 2
  final val CHECKS_FIELD_NUMBER = 3
  final val TIMESTAMP_FIELD_NUMBER = 4
  @transient
  private[process_rpc] val _typemapper_checks: _root_.scalapb.TypeMapper[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry, (_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult)] = implicitly[_root_.scalapb.TypeMapper[a8.hermes.proto.process.process_rpc.HealthCheckResponse.ChecksEntry, (_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult)]]
  def of(
    status: a8.hermes.proto.process.process_rpc.HealthStatus,
    message: _root_.scala.Predef.String,
    checks: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, a8.hermes.proto.process.process_rpc.HealthCheckResult],
    timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]
  ): _root_.a8.hermes.proto.process.process_rpc.HealthCheckResponse = _root_.a8.hermes.proto.process.process_rpc.HealthCheckResponse(
    status,
    message,
    checks,
    timestamp
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[process_rpc.HealthCheckResponse])
}
