// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.process_rpc

/** Health check messages
  */
sealed abstract class HealthStatus(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = a8.hermes.proto.process.process_rpc.HealthStatus
  type RecognizedType = a8.hermes.proto.process.process_rpc.HealthStatus.Recognized
  def isHealthStatusUnspecified: _root_.scala.Boolean = false
  def isHealthStatusHealthy: _root_.scala.Boolean = false
  def isHealthStatusDegraded: _root_.scala.Boolean = false
  def isHealthStatusUnhealthy: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[HealthStatus] = a8.hermes.proto.process.process_rpc.HealthStatus
  final def asRecognized: _root_.scala.Option[a8.hermes.proto.process.process_rpc.HealthStatus.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[a8.hermes.proto.process.process_rpc.HealthStatus.Recognized])
}

object HealthStatus extends _root_.scalapb.GeneratedEnumCompanion[HealthStatus] {
  sealed trait Recognized extends HealthStatus
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[HealthStatus] = this
  
  @SerialVersionUID(0L)
  case object HEALTH_STATUS_UNSPECIFIED extends HealthStatus(0) with HealthStatus.Recognized {
    val index = 0
    val name = "HEALTH_STATUS_UNSPECIFIED"
    override def isHealthStatusUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HEALTH_STATUS_HEALTHY extends HealthStatus(1) with HealthStatus.Recognized {
    val index = 1
    val name = "HEALTH_STATUS_HEALTHY"
    override def isHealthStatusHealthy: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HEALTH_STATUS_DEGRADED extends HealthStatus(2) with HealthStatus.Recognized {
    val index = 2
    val name = "HEALTH_STATUS_DEGRADED"
    override def isHealthStatusDegraded: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HEALTH_STATUS_UNHEALTHY extends HealthStatus(3) with HealthStatus.Recognized {
    val index = 3
    val name = "HEALTH_STATUS_UNHEALTHY"
    override def isHealthStatusUnhealthy: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends HealthStatus(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(HEALTH_STATUS_UNSPECIFIED, HEALTH_STATUS_HEALTHY, HEALTH_STATUS_DEGRADED, HEALTH_STATUS_UNHEALTHY)
  def fromValue(__value: _root_.scala.Int): HealthStatus = __value match {
    case 0 => HEALTH_STATUS_UNSPECIFIED
    case 1 => HEALTH_STATUS_HEALTHY
    case 2 => HEALTH_STATUS_DEGRADED
    case 3 => HEALTH_STATUS_UNHEALTHY
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = ProcessRpcProto.javaDescriptor.getEnumTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = ProcessRpcProto.scalaDescriptor.enums(1)
}