// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.process_rpc

/** @param level
  *   New log level to set
  * @param component
  *   Specific component/logger to update (optional, empty = root logger)
  */
@SerialVersionUID(0L)
final case class SetLogLevelRequest(
    level: a8.hermes.proto.process.process_rpc.LogLevel = a8.hermes.proto.process.process_rpc.LogLevel.LOG_LEVEL_UNSPECIFIED,
    component: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SetLogLevelRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = level.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(1, __value)
        }
      };
      
      {
        val __value = component
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = level.value
        if (__v != 0) {
          _output__.writeEnum(1, __v)
        }
      };
      {
        val __v = component
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withLevel(__v: a8.hermes.proto.process.process_rpc.LogLevel): SetLogLevelRequest = copy(level = __v)
    def withComponent(__v: _root_.scala.Predef.String): SetLogLevelRequest = copy(component = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = level.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 2 => {
          val __t = component
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PEnum(level.scalaValueDescriptor)
        case 2 => _root_.scalapb.descriptors.PString(component)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.process_rpc.SetLogLevelRequest.type = a8.hermes.proto.process.process_rpc.SetLogLevelRequest
    // @@protoc_insertion_point(GeneratedMessage[process_rpc.SetLogLevelRequest])
}

object SetLogLevelRequest extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.SetLogLevelRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.SetLogLevelRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.process_rpc.SetLogLevelRequest = {
    var __level: a8.hermes.proto.process.process_rpc.LogLevel = a8.hermes.proto.process.process_rpc.LogLevel.LOG_LEVEL_UNSPECIFIED
    var __component: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __level = a8.hermes.proto.process.process_rpc.LogLevel.fromValue(_input__.readEnum())
        case 18 =>
          __component = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.process_rpc.SetLogLevelRequest(
        level = __level,
        component = __component,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.process_rpc.SetLogLevelRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.process_rpc.SetLogLevelRequest(
        level = a8.hermes.proto.process.process_rpc.LogLevel.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(a8.hermes.proto.process.process_rpc.LogLevel.LOG_LEVEL_UNSPECIFIED.scalaValueDescriptor).number),
        component = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ProcessRpcProto.javaDescriptor.getMessageTypes().get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ProcessRpcProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => a8.hermes.proto.process.process_rpc.LogLevel
    }
  }
  lazy val defaultInstance = a8.hermes.proto.process.process_rpc.SetLogLevelRequest(
    level = a8.hermes.proto.process.process_rpc.LogLevel.LOG_LEVEL_UNSPECIFIED,
    component = ""
  )
  implicit class SetLogLevelRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.SetLogLevelRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.process_rpc.SetLogLevelRequest](_l) {
    def level: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.LogLevel] = field(_.level)((c_, f_) => c_.copy(level = f_))
    def component: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.component)((c_, f_) => c_.copy(component = f_))
  }
  final val LEVEL_FIELD_NUMBER = 1
  final val COMPONENT_FIELD_NUMBER = 2
  def of(
    level: a8.hermes.proto.process.process_rpc.LogLevel,
    component: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.process.process_rpc.SetLogLevelRequest = _root_.a8.hermes.proto.process.process_rpc.SetLogLevelRequest(
    level,
    component
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[process_rpc.SetLogLevelRequest])
}
