// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.auth.auth

/** GetUserInfoForSelfResponse returns authenticated user's information
  *
  * @param userUid
  *   User UID
  * @param name
  *   User name
  * @param email
  *   User email (may be empty)
  * @param description
  *   User description
  * @param groups
  *   Direct group memberships
  * @param externalMaintainer
  *   External maintainer (may be empty)
  * @param extraConfig
  *   Extra config as JSON
  * @param expiresAt
  *   When the auth token expires
  * @param expiresExtension
  *   Extension duration (e.g., "1 hour")
  */
@SerialVersionUID(0L)
final case class GetUserInfoForSelfResponse(
    userUid: _root_.scala.Predef.String = "",
    name: _root_.scala.Predef.String = "",
    email: _root_.scala.Predef.String = "",
    description: _root_.scala.Predef.String = "",
    groups: _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo] = _root_.scala.Seq.empty,
    externalMaintainer: _root_.scala.Predef.String = "",
    extraConfig: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    expiresAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    expiresExtension: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[GetUserInfoForSelfResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = userUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = email
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = description
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      groups.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = externalMaintainer
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = extraConfig
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(7, __value)
        }
      };
      if (expiresAt.isDefined) {
        val __value = expiresAt.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = expiresExtension
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = userUid
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = email
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = description
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      groups.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = externalMaintainer
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = extraConfig
        if (!__v.isEmpty) {
          _output__.writeBytes(7, __v)
        }
      };
      expiresAt.foreach { __v =>
        val __m = __v
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = expiresExtension
        if (!__v.isEmpty) {
          _output__.writeString(9, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withUserUid(__v: _root_.scala.Predef.String): GetUserInfoForSelfResponse = copy(userUid = __v)
    def withName(__v: _root_.scala.Predef.String): GetUserInfoForSelfResponse = copy(name = __v)
    def withEmail(__v: _root_.scala.Predef.String): GetUserInfoForSelfResponse = copy(email = __v)
    def withDescription(__v: _root_.scala.Predef.String): GetUserInfoForSelfResponse = copy(description = __v)
    def clearGroups = copy(groups = _root_.scala.Seq.empty)
    def addGroups(__vs: a8.hermes.proto.auth.auth.UserGroupInfo *): GetUserInfoForSelfResponse = addAllGroups(__vs)
    def addAllGroups(__vs: Iterable[a8.hermes.proto.auth.auth.UserGroupInfo]): GetUserInfoForSelfResponse = copy(groups = groups ++ __vs)
    def withGroups(__v: _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo]): GetUserInfoForSelfResponse = copy(groups = __v)
    def withExternalMaintainer(__v: _root_.scala.Predef.String): GetUserInfoForSelfResponse = copy(externalMaintainer = __v)
    def withExtraConfig(__v: _root_.com.google.protobuf.ByteString): GetUserInfoForSelfResponse = copy(extraConfig = __v)
    def getExpiresAt: com.google.protobuf.timestamp.Timestamp = expiresAt.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearExpiresAt: GetUserInfoForSelfResponse = copy(expiresAt = _root_.scala.None)
    def withExpiresAt(__v: com.google.protobuf.timestamp.Timestamp): GetUserInfoForSelfResponse = copy(expiresAt = Option(__v))
    def withExpiresExtension(__v: _root_.scala.Predef.String): GetUserInfoForSelfResponse = copy(expiresExtension = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = userUid
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = email
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = description
          if (__t != "") __t else null
        }
        case 5 => groups
        case 6 => {
          val __t = externalMaintainer
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = extraConfig
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 8 => expiresAt.orNull
        case 9 => {
          val __t = expiresExtension
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(userUid)
        case 2 => _root_.scalapb.descriptors.PString(name)
        case 3 => _root_.scalapb.descriptors.PString(email)
        case 4 => _root_.scalapb.descriptors.PString(description)
        case 5 => _root_.scalapb.descriptors.PRepeated(groups.iterator.map(_.toPMessage).toVector)
        case 6 => _root_.scalapb.descriptors.PString(externalMaintainer)
        case 7 => _root_.scalapb.descriptors.PByteString(extraConfig)
        case 8 => expiresAt.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 9 => _root_.scalapb.descriptors.PString(expiresExtension)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse.type = a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse
    // @@protoc_insertion_point(GeneratedMessage[auth.GetUserInfoForSelfResponse])
}

object GetUserInfoForSelfResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse = {
    var __userUid: _root_.scala.Predef.String = ""
    var __name: _root_.scala.Predef.String = ""
    var __email: _root_.scala.Predef.String = ""
    var __description: _root_.scala.Predef.String = ""
    val __groups: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.UserGroupInfo] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.UserGroupInfo]
    var __externalMaintainer: _root_.scala.Predef.String = ""
    var __extraConfig: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
    var __expiresAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var __expiresExtension: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __userUid = _input__.readStringRequireUtf8()
        case 18 =>
          __name = _input__.readStringRequireUtf8()
        case 26 =>
          __email = _input__.readStringRequireUtf8()
        case 34 =>
          __description = _input__.readStringRequireUtf8()
        case 42 =>
          __groups += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.auth.auth.UserGroupInfo](_input__)
        case 50 =>
          __externalMaintainer = _input__.readStringRequireUtf8()
        case 58 =>
          __extraConfig = _input__.readBytes()
        case 66 =>
          __expiresAt = _root_.scala.Option(__expiresAt.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 74 =>
          __expiresExtension = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse(
        userUid = __userUid,
        name = __name,
        email = __email,
        description = __description,
        groups = __groups.result(),
        externalMaintainer = __externalMaintainer,
        extraConfig = __extraConfig,
        expiresAt = __expiresAt,
        expiresExtension = __expiresExtension,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse(
        userUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        email = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        groups = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo]]).getOrElse(_root_.scala.Seq.empty),
        externalMaintainer = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        extraConfig = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        expiresAt = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        expiresExtension = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AuthProto.javaDescriptor.getMessageTypes().get(12)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AuthProto.scalaDescriptor.messages(12)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 5 => __out = a8.hermes.proto.auth.auth.UserGroupInfo
      case 8 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse(
    userUid = "",
    name = "",
    email = "",
    description = "",
    groups = _root_.scala.Seq.empty,
    externalMaintainer = "",
    extraConfig = _root_.com.google.protobuf.ByteString.EMPTY,
    expiresAt = _root_.scala.None,
    expiresExtension = ""
  )
  implicit class GetUserInfoForSelfResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse](_l) {
    def userUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userUid)((c_, f_) => c_.copy(userUid = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def email: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.email)((c_, f_) => c_.copy(email = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
    def groups: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo]] = field(_.groups)((c_, f_) => c_.copy(groups = f_))
    def externalMaintainer: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.externalMaintainer)((c_, f_) => c_.copy(externalMaintainer = f_))
    def extraConfig: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.extraConfig)((c_, f_) => c_.copy(extraConfig = f_))
    def expiresAt: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getExpiresAt)((c_, f_) => c_.copy(expiresAt = _root_.scala.Option(f_)))
    def optionalExpiresAt: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.expiresAt)((c_, f_) => c_.copy(expiresAt = f_))
    def expiresExtension: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.expiresExtension)((c_, f_) => c_.copy(expiresExtension = f_))
  }
  final val USER_UID_FIELD_NUMBER = 1
  final val NAME_FIELD_NUMBER = 2
  final val EMAIL_FIELD_NUMBER = 3
  final val DESCRIPTION_FIELD_NUMBER = 4
  final val GROUPS_FIELD_NUMBER = 5
  final val EXTERNAL_MAINTAINER_FIELD_NUMBER = 6
  final val EXTRA_CONFIG_FIELD_NUMBER = 7
  final val EXPIRES_AT_FIELD_NUMBER = 8
  final val EXPIRES_EXTENSION_FIELD_NUMBER = 9
  def of(
    userUid: _root_.scala.Predef.String,
    name: _root_.scala.Predef.String,
    email: _root_.scala.Predef.String,
    description: _root_.scala.Predef.String,
    groups: _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo],
    externalMaintainer: _root_.scala.Predef.String,
    extraConfig: _root_.com.google.protobuf.ByteString,
    expiresAt: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    expiresExtension: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse = _root_.a8.hermes.proto.auth.auth.GetUserInfoForSelfResponse(
    userUid,
    name,
    email,
    description,
    groups,
    externalMaintainer,
    extraConfig,
    expiresAt,
    expiresExtension
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[auth.GetUserInfoForSelfResponse])
}
