// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.auth.auth

/** ImpersonateUserResponse returns a session token bound to the target user.
  *
  * @param sessionToken
  *   token authenticating AS the target user
  * @param targetUserUid
  *   the impersonated user's uid (Y)
  * @param targetName
  *   the impersonated user's name
  * @param targetEmail
  *   the impersonated user's email (may be empty)
  * @param targetGroups
  *   the impersonated user's groups
  * @param impersonatorUid
  *   the admin who minted this (X)
  * @param impersonatorName
  *   the admin's name (for the "viewing as" banner)
  * @param expiresAt
  *   ISO 8601 token expiry
  */
@SerialVersionUID(0L)
final case class ImpersonateUserResponse(
    sessionToken: _root_.scala.Predef.String = "",
    targetUserUid: _root_.scala.Predef.String = "",
    targetName: _root_.scala.Predef.String = "",
    targetEmail: _root_.scala.Predef.String = "",
    targetGroups: _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo] = _root_.scala.Seq.empty,
    impersonatorUid: _root_.scala.Predef.String = "",
    impersonatorName: _root_.scala.Predef.String = "",
    expiresAt: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ImpersonateUserResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = sessionToken
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = targetUserUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = targetName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = targetEmail
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      targetGroups.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = impersonatorUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = impersonatorName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      
      {
        val __value = expiresAt
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = sessionToken
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = targetUserUid
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = targetName
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = targetEmail
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      targetGroups.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = impersonatorUid
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = impersonatorName
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = expiresAt
        if (!__v.isEmpty) {
          _output__.writeString(8, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withSessionToken(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(sessionToken = __v)
    def withTargetUserUid(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(targetUserUid = __v)
    def withTargetName(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(targetName = __v)
    def withTargetEmail(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(targetEmail = __v)
    def clearTargetGroups = copy(targetGroups = _root_.scala.Seq.empty)
    def addTargetGroups(__vs: a8.hermes.proto.auth.auth.UserGroupInfo *): ImpersonateUserResponse = addAllTargetGroups(__vs)
    def addAllTargetGroups(__vs: Iterable[a8.hermes.proto.auth.auth.UserGroupInfo]): ImpersonateUserResponse = copy(targetGroups = targetGroups ++ __vs)
    def withTargetGroups(__v: _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo]): ImpersonateUserResponse = copy(targetGroups = __v)
    def withImpersonatorUid(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(impersonatorUid = __v)
    def withImpersonatorName(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(impersonatorName = __v)
    def withExpiresAt(__v: _root_.scala.Predef.String): ImpersonateUserResponse = copy(expiresAt = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = sessionToken
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = targetUserUid
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = targetName
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = targetEmail
          if (__t != "") __t else null
        }
        case 5 => targetGroups
        case 6 => {
          val __t = impersonatorUid
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = impersonatorName
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = expiresAt
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(sessionToken)
        case 2 => _root_.scalapb.descriptors.PString(targetUserUid)
        case 3 => _root_.scalapb.descriptors.PString(targetName)
        case 4 => _root_.scalapb.descriptors.PString(targetEmail)
        case 5 => _root_.scalapb.descriptors.PRepeated(targetGroups.iterator.map(_.toPMessage).toVector)
        case 6 => _root_.scalapb.descriptors.PString(impersonatorUid)
        case 7 => _root_.scalapb.descriptors.PString(impersonatorName)
        case 8 => _root_.scalapb.descriptors.PString(expiresAt)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.auth.auth.ImpersonateUserResponse.type = a8.hermes.proto.auth.auth.ImpersonateUserResponse
    // @@protoc_insertion_point(GeneratedMessage[auth.ImpersonateUserResponse])
}

object ImpersonateUserResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.ImpersonateUserResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.ImpersonateUserResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.auth.auth.ImpersonateUserResponse = {
    var __sessionToken: _root_.scala.Predef.String = ""
    var __targetUserUid: _root_.scala.Predef.String = ""
    var __targetName: _root_.scala.Predef.String = ""
    var __targetEmail: _root_.scala.Predef.String = ""
    val __targetGroups: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.UserGroupInfo] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.UserGroupInfo]
    var __impersonatorUid: _root_.scala.Predef.String = ""
    var __impersonatorName: _root_.scala.Predef.String = ""
    var __expiresAt: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __sessionToken = _input__.readStringRequireUtf8()
        case 18 =>
          __targetUserUid = _input__.readStringRequireUtf8()
        case 26 =>
          __targetName = _input__.readStringRequireUtf8()
        case 34 =>
          __targetEmail = _input__.readStringRequireUtf8()
        case 42 =>
          __targetGroups += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.auth.auth.UserGroupInfo](_input__)
        case 50 =>
          __impersonatorUid = _input__.readStringRequireUtf8()
        case 58 =>
          __impersonatorName = _input__.readStringRequireUtf8()
        case 66 =>
          __expiresAt = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.auth.auth.ImpersonateUserResponse(
        sessionToken = __sessionToken,
        targetUserUid = __targetUserUid,
        targetName = __targetName,
        targetEmail = __targetEmail,
        targetGroups = __targetGroups.result(),
        impersonatorUid = __impersonatorUid,
        impersonatorName = __impersonatorName,
        expiresAt = __expiresAt,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.auth.auth.ImpersonateUserResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.auth.auth.ImpersonateUserResponse(
        sessionToken = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        targetUserUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        targetName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        targetEmail = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        targetGroups = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo]]).getOrElse(_root_.scala.Seq.empty),
        impersonatorUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        impersonatorName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        expiresAt = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AuthProto.javaDescriptor.getMessageTypes().get(16)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AuthProto.scalaDescriptor.messages(16)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 5 => __out = a8.hermes.proto.auth.auth.UserGroupInfo
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.auth.auth.ImpersonateUserResponse(
    sessionToken = "",
    targetUserUid = "",
    targetName = "",
    targetEmail = "",
    targetGroups = _root_.scala.Seq.empty,
    impersonatorUid = "",
    impersonatorName = "",
    expiresAt = ""
  )
  implicit class ImpersonateUserResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.auth.auth.ImpersonateUserResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.auth.auth.ImpersonateUserResponse](_l) {
    def sessionToken: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.sessionToken)((c_, f_) => c_.copy(sessionToken = f_))
    def targetUserUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.targetUserUid)((c_, f_) => c_.copy(targetUserUid = f_))
    def targetName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.targetName)((c_, f_) => c_.copy(targetName = f_))
    def targetEmail: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.targetEmail)((c_, f_) => c_.copy(targetEmail = f_))
    def targetGroups: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo]] = field(_.targetGroups)((c_, f_) => c_.copy(targetGroups = f_))
    def impersonatorUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.impersonatorUid)((c_, f_) => c_.copy(impersonatorUid = f_))
    def impersonatorName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.impersonatorName)((c_, f_) => c_.copy(impersonatorName = f_))
    def expiresAt: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.expiresAt)((c_, f_) => c_.copy(expiresAt = f_))
  }
  final val SESSION_TOKEN_FIELD_NUMBER = 1
  final val TARGET_USER_UID_FIELD_NUMBER = 2
  final val TARGET_NAME_FIELD_NUMBER = 3
  final val TARGET_EMAIL_FIELD_NUMBER = 4
  final val TARGET_GROUPS_FIELD_NUMBER = 5
  final val IMPERSONATOR_UID_FIELD_NUMBER = 6
  final val IMPERSONATOR_NAME_FIELD_NUMBER = 7
  final val EXPIRES_AT_FIELD_NUMBER = 8
  def of(
    sessionToken: _root_.scala.Predef.String,
    targetUserUid: _root_.scala.Predef.String,
    targetName: _root_.scala.Predef.String,
    targetEmail: _root_.scala.Predef.String,
    targetGroups: _root_.scala.Seq[a8.hermes.proto.auth.auth.UserGroupInfo],
    impersonatorUid: _root_.scala.Predef.String,
    impersonatorName: _root_.scala.Predef.String,
    expiresAt: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.auth.auth.ImpersonateUserResponse = _root_.a8.hermes.proto.auth.auth.ImpersonateUserResponse(
    sessionToken,
    targetUserUid,
    targetName,
    targetEmail,
    targetGroups,
    impersonatorUid,
    impersonatorName,
    expiresAt
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[auth.ImpersonateUserResponse])
}
