// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.auth.auth

/** ListPoliciesResponse returns stored policies
  */
@SerialVersionUID(0L)
final case class ListPoliciesResponse(
    policies: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyInfo] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ListPoliciesResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      policies.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      policies.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearPolicies = copy(policies = _root_.scala.Seq.empty)
    def addPolicies(__vs: a8.hermes.proto.auth.auth.PolicyInfo *): ListPoliciesResponse = addAllPolicies(__vs)
    def addAllPolicies(__vs: Iterable[a8.hermes.proto.auth.auth.PolicyInfo]): ListPoliciesResponse = copy(policies = policies ++ __vs)
    def withPolicies(__v: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyInfo]): ListPoliciesResponse = copy(policies = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => policies
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(policies.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.auth.auth.ListPoliciesResponse.type = a8.hermes.proto.auth.auth.ListPoliciesResponse
    // @@protoc_insertion_point(GeneratedMessage[auth.ListPoliciesResponse])
}

object ListPoliciesResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.ListPoliciesResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.ListPoliciesResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.auth.auth.ListPoliciesResponse = {
    val __policies: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.PolicyInfo] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.PolicyInfo]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __policies += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.auth.auth.PolicyInfo](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.auth.auth.ListPoliciesResponse(
        policies = __policies.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.auth.auth.ListPoliciesResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.auth.auth.ListPoliciesResponse(
        policies = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyInfo]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AuthProto.javaDescriptor.getMessageTypes().get(31)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AuthProto.scalaDescriptor.messages(31)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = a8.hermes.proto.auth.auth.PolicyInfo
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.auth.auth.ListPoliciesResponse(
    policies = _root_.scala.Seq.empty
  )
  implicit class ListPoliciesResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.auth.auth.ListPoliciesResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.auth.auth.ListPoliciesResponse](_l) {
    def policies: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyInfo]] = field(_.policies)((c_, f_) => c_.copy(policies = f_))
  }
  final val POLICIES_FIELD_NUMBER = 1
  def of(
    policies: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyInfo]
  ): _root_.a8.hermes.proto.auth.auth.ListPoliciesResponse = _root_.a8.hermes.proto.auth.auth.ListPoliciesResponse(
    policies
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[auth.ListPoliciesResponse])
}
