// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.auth.auth

/** TestEndpointAccessResponse returns authorization test results
  *
  * @param allowed
  *   Whether access is allowed
  * @param reason
  *   Explanation of the decision
  * @param userUid
  *   Resolved user UID
  * @param userEmail
  *   User email
  * @param userName
  *   User display name
  * @param userGroupNames
  *   User's group names (for display)
  * @param userGroupUids
  *   User's group UIDs (for filtering)
  * @param winningPolicy
  *   The policy that made the final decision
  * @param matchedPolicies
  *   All policies that matched
  * @param evaluatedPolicies
  *   All evaluated policies (if requested)
  * @param noPolicyMatched
  *   True if no policy matched (fallback to deny)
  */
@SerialVersionUID(0L)
final case class TestEndpointAccessResponse(
    allowed: _root_.scala.Boolean = false,
    reason: _root_.scala.Predef.String = "",
    userUid: _root_.scala.Predef.String = "",
    userEmail: _root_.scala.Predef.String = "",
    userName: _root_.scala.Predef.String = "",
    userGroupNames: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    userGroupUids: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    winningPolicy: _root_.scala.Option[a8.hermes.proto.auth.auth.PolicyMatchInfo] = _root_.scala.None,
    matchedPolicies: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo] = _root_.scala.Seq.empty,
    evaluatedPolicies: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo] = _root_.scala.Seq.empty,
    noPolicyMatched: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[TestEndpointAccessResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = allowed
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(1, __value)
        }
      };
      
      {
        val __value = reason
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = userUid
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = userEmail
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = userName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      userGroupNames.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
      }
      userGroupUids.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
      }
      if (winningPolicy.isDefined) {
        val __value = winningPolicy.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      matchedPolicies.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      evaluatedPolicies.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = noPolicyMatched
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(11, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = allowed
        if (__v != false) {
          _output__.writeBool(1, __v)
        }
      };
      {
        val __v = reason
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = userUid
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = userEmail
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = userName
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      userGroupNames.foreach { __v =>
        val __m = __v
        _output__.writeString(6, __m)
      };
      userGroupUids.foreach { __v =>
        val __m = __v
        _output__.writeString(7, __m)
      };
      winningPolicy.foreach { __v =>
        val __m = __v
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      matchedPolicies.foreach { __v =>
        val __m = __v
        _output__.writeTag(9, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      evaluatedPolicies.foreach { __v =>
        val __m = __v
        _output__.writeTag(10, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = noPolicyMatched
        if (__v != false) {
          _output__.writeBool(11, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withAllowed(__v: _root_.scala.Boolean): TestEndpointAccessResponse = copy(allowed = __v)
    def withReason(__v: _root_.scala.Predef.String): TestEndpointAccessResponse = copy(reason = __v)
    def withUserUid(__v: _root_.scala.Predef.String): TestEndpointAccessResponse = copy(userUid = __v)
    def withUserEmail(__v: _root_.scala.Predef.String): TestEndpointAccessResponse = copy(userEmail = __v)
    def withUserName(__v: _root_.scala.Predef.String): TestEndpointAccessResponse = copy(userName = __v)
    def clearUserGroupNames = copy(userGroupNames = _root_.scala.Seq.empty)
    def addUserGroupNames(__vs: _root_.scala.Predef.String *): TestEndpointAccessResponse = addAllUserGroupNames(__vs)
    def addAllUserGroupNames(__vs: Iterable[_root_.scala.Predef.String]): TestEndpointAccessResponse = copy(userGroupNames = userGroupNames ++ __vs)
    def withUserGroupNames(__v: _root_.scala.Seq[_root_.scala.Predef.String]): TestEndpointAccessResponse = copy(userGroupNames = __v)
    def clearUserGroupUids = copy(userGroupUids = _root_.scala.Seq.empty)
    def addUserGroupUids(__vs: _root_.scala.Predef.String *): TestEndpointAccessResponse = addAllUserGroupUids(__vs)
    def addAllUserGroupUids(__vs: Iterable[_root_.scala.Predef.String]): TestEndpointAccessResponse = copy(userGroupUids = userGroupUids ++ __vs)
    def withUserGroupUids(__v: _root_.scala.Seq[_root_.scala.Predef.String]): TestEndpointAccessResponse = copy(userGroupUids = __v)
    def getWinningPolicy: a8.hermes.proto.auth.auth.PolicyMatchInfo = winningPolicy.getOrElse(a8.hermes.proto.auth.auth.PolicyMatchInfo.defaultInstance)
    def clearWinningPolicy: TestEndpointAccessResponse = copy(winningPolicy = _root_.scala.None)
    def withWinningPolicy(__v: a8.hermes.proto.auth.auth.PolicyMatchInfo): TestEndpointAccessResponse = copy(winningPolicy = Option(__v))
    def clearMatchedPolicies = copy(matchedPolicies = _root_.scala.Seq.empty)
    def addMatchedPolicies(__vs: a8.hermes.proto.auth.auth.PolicyMatchInfo *): TestEndpointAccessResponse = addAllMatchedPolicies(__vs)
    def addAllMatchedPolicies(__vs: Iterable[a8.hermes.proto.auth.auth.PolicyMatchInfo]): TestEndpointAccessResponse = copy(matchedPolicies = matchedPolicies ++ __vs)
    def withMatchedPolicies(__v: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo]): TestEndpointAccessResponse = copy(matchedPolicies = __v)
    def clearEvaluatedPolicies = copy(evaluatedPolicies = _root_.scala.Seq.empty)
    def addEvaluatedPolicies(__vs: a8.hermes.proto.auth.auth.PolicyMatchInfo *): TestEndpointAccessResponse = addAllEvaluatedPolicies(__vs)
    def addAllEvaluatedPolicies(__vs: Iterable[a8.hermes.proto.auth.auth.PolicyMatchInfo]): TestEndpointAccessResponse = copy(evaluatedPolicies = evaluatedPolicies ++ __vs)
    def withEvaluatedPolicies(__v: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo]): TestEndpointAccessResponse = copy(evaluatedPolicies = __v)
    def withNoPolicyMatched(__v: _root_.scala.Boolean): TestEndpointAccessResponse = copy(noPolicyMatched = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = allowed
          if (__t != false) __t else null
        }
        case 2 => {
          val __t = reason
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = userUid
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = userEmail
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = userName
          if (__t != "") __t else null
        }
        case 6 => userGroupNames
        case 7 => userGroupUids
        case 8 => winningPolicy.orNull
        case 9 => matchedPolicies
        case 10 => evaluatedPolicies
        case 11 => {
          val __t = noPolicyMatched
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PBoolean(allowed)
        case 2 => _root_.scalapb.descriptors.PString(reason)
        case 3 => _root_.scalapb.descriptors.PString(userUid)
        case 4 => _root_.scalapb.descriptors.PString(userEmail)
        case 5 => _root_.scalapb.descriptors.PString(userName)
        case 6 => _root_.scalapb.descriptors.PRepeated(userGroupNames.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 7 => _root_.scalapb.descriptors.PRepeated(userGroupUids.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 8 => winningPolicy.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 9 => _root_.scalapb.descriptors.PRepeated(matchedPolicies.iterator.map(_.toPMessage).toVector)
        case 10 => _root_.scalapb.descriptors.PRepeated(evaluatedPolicies.iterator.map(_.toPMessage).toVector)
        case 11 => _root_.scalapb.descriptors.PBoolean(noPolicyMatched)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.auth.auth.TestEndpointAccessResponse.type = a8.hermes.proto.auth.auth.TestEndpointAccessResponse
    // @@protoc_insertion_point(GeneratedMessage[auth.TestEndpointAccessResponse])
}

object TestEndpointAccessResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.TestEndpointAccessResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.auth.auth.TestEndpointAccessResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.auth.auth.TestEndpointAccessResponse = {
    var __allowed: _root_.scala.Boolean = false
    var __reason: _root_.scala.Predef.String = ""
    var __userUid: _root_.scala.Predef.String = ""
    var __userEmail: _root_.scala.Predef.String = ""
    var __userName: _root_.scala.Predef.String = ""
    val __userGroupNames: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    val __userGroupUids: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    var __winningPolicy: _root_.scala.Option[a8.hermes.proto.auth.auth.PolicyMatchInfo] = _root_.scala.None
    val __matchedPolicies: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.PolicyMatchInfo] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.PolicyMatchInfo]
    val __evaluatedPolicies: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.PolicyMatchInfo] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.auth.auth.PolicyMatchInfo]
    var __noPolicyMatched: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __allowed = _input__.readBool()
        case 18 =>
          __reason = _input__.readStringRequireUtf8()
        case 26 =>
          __userUid = _input__.readStringRequireUtf8()
        case 34 =>
          __userEmail = _input__.readStringRequireUtf8()
        case 42 =>
          __userName = _input__.readStringRequireUtf8()
        case 50 =>
          __userGroupNames += _input__.readStringRequireUtf8()
        case 58 =>
          __userGroupUids += _input__.readStringRequireUtf8()
        case 66 =>
          __winningPolicy = _root_.scala.Option(__winningPolicy.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.auth.auth.PolicyMatchInfo](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 74 =>
          __matchedPolicies += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.auth.auth.PolicyMatchInfo](_input__)
        case 82 =>
          __evaluatedPolicies += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.auth.auth.PolicyMatchInfo](_input__)
        case 88 =>
          __noPolicyMatched = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.auth.auth.TestEndpointAccessResponse(
        allowed = __allowed,
        reason = __reason,
        userUid = __userUid,
        userEmail = __userEmail,
        userName = __userName,
        userGroupNames = __userGroupNames.result(),
        userGroupUids = __userGroupUids.result(),
        winningPolicy = __winningPolicy,
        matchedPolicies = __matchedPolicies.result(),
        evaluatedPolicies = __evaluatedPolicies.result(),
        noPolicyMatched = __noPolicyMatched,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.auth.auth.TestEndpointAccessResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.auth.auth.TestEndpointAccessResponse(
        allowed = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        reason = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        userUid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        userEmail = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        userName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        userGroupNames = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        userGroupUids = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        winningPolicy = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.auth.auth.PolicyMatchInfo]]),
        matchedPolicies = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo]]).getOrElse(_root_.scala.Seq.empty),
        evaluatedPolicies = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo]]).getOrElse(_root_.scala.Seq.empty),
        noPolicyMatched = __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AuthProto.javaDescriptor.getMessageTypes().get(22)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AuthProto.scalaDescriptor.messages(22)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 8 => __out = a8.hermes.proto.auth.auth.PolicyMatchInfo
      case 9 => __out = a8.hermes.proto.auth.auth.PolicyMatchInfo
      case 10 => __out = a8.hermes.proto.auth.auth.PolicyMatchInfo
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.auth.auth.TestEndpointAccessResponse(
    allowed = false,
    reason = "",
    userUid = "",
    userEmail = "",
    userName = "",
    userGroupNames = _root_.scala.Seq.empty,
    userGroupUids = _root_.scala.Seq.empty,
    winningPolicy = _root_.scala.None,
    matchedPolicies = _root_.scala.Seq.empty,
    evaluatedPolicies = _root_.scala.Seq.empty,
    noPolicyMatched = false
  )
  implicit class TestEndpointAccessResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.auth.auth.TestEndpointAccessResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.auth.auth.TestEndpointAccessResponse](_l) {
    def allowed: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.allowed)((c_, f_) => c_.copy(allowed = f_))
    def reason: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.reason)((c_, f_) => c_.copy(reason = f_))
    def userUid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userUid)((c_, f_) => c_.copy(userUid = f_))
    def userEmail: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userEmail)((c_, f_) => c_.copy(userEmail = f_))
    def userName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userName)((c_, f_) => c_.copy(userName = f_))
    def userGroupNames: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.userGroupNames)((c_, f_) => c_.copy(userGroupNames = f_))
    def userGroupUids: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.userGroupUids)((c_, f_) => c_.copy(userGroupUids = f_))
    def winningPolicy: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.auth.auth.PolicyMatchInfo] = field(_.getWinningPolicy)((c_, f_) => c_.copy(winningPolicy = _root_.scala.Option(f_)))
    def optionalWinningPolicy: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.auth.auth.PolicyMatchInfo]] = field(_.winningPolicy)((c_, f_) => c_.copy(winningPolicy = f_))
    def matchedPolicies: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo]] = field(_.matchedPolicies)((c_, f_) => c_.copy(matchedPolicies = f_))
    def evaluatedPolicies: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo]] = field(_.evaluatedPolicies)((c_, f_) => c_.copy(evaluatedPolicies = f_))
    def noPolicyMatched: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.noPolicyMatched)((c_, f_) => c_.copy(noPolicyMatched = f_))
  }
  final val ALLOWED_FIELD_NUMBER = 1
  final val REASON_FIELD_NUMBER = 2
  final val USER_UID_FIELD_NUMBER = 3
  final val USER_EMAIL_FIELD_NUMBER = 4
  final val USER_NAME_FIELD_NUMBER = 5
  final val USER_GROUP_NAMES_FIELD_NUMBER = 6
  final val USER_GROUP_UIDS_FIELD_NUMBER = 7
  final val WINNING_POLICY_FIELD_NUMBER = 8
  final val MATCHED_POLICIES_FIELD_NUMBER = 9
  final val EVALUATED_POLICIES_FIELD_NUMBER = 10
  final val NO_POLICY_MATCHED_FIELD_NUMBER = 11
  def of(
    allowed: _root_.scala.Boolean,
    reason: _root_.scala.Predef.String,
    userUid: _root_.scala.Predef.String,
    userEmail: _root_.scala.Predef.String,
    userName: _root_.scala.Predef.String,
    userGroupNames: _root_.scala.Seq[_root_.scala.Predef.String],
    userGroupUids: _root_.scala.Seq[_root_.scala.Predef.String],
    winningPolicy: _root_.scala.Option[a8.hermes.proto.auth.auth.PolicyMatchInfo],
    matchedPolicies: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo],
    evaluatedPolicies: _root_.scala.Seq[a8.hermes.proto.auth.auth.PolicyMatchInfo],
    noPolicyMatched: _root_.scala.Boolean
  ): _root_.a8.hermes.proto.auth.auth.TestEndpointAccessResponse = _root_.a8.hermes.proto.auth.auth.TestEndpointAccessResponse(
    allowed,
    reason,
    userUid,
    userEmail,
    userName,
    userGroupNames,
    userGroupUids,
    winningPolicy,
    matchedPolicies,
    evaluatedPolicies,
    noPolicyMatched
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[auth.TestEndpointAccessResponse])
}
