package a8.hermes.continuum

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers

/**
 * Pins `ContinuumRunnerClient.placementTagForSeed` to godev's `a8nats.PlacementTagForSeed`.
 *
 * CROSS-LANGUAGE CONTRACT. This is the Scala half of a two-sided pin. The Go half is:
 *
 *   godev/a8nats/placement_test.go
 *     - `placementGoldens`                        (the same table, same order)
 *     - `TestPlacementTagForSeedGoldens`          <-> "matches godev PlacementTagForSeed ..."
 *     - `TestPlacementTagForSeedUnsignedModulo`   <-> "seeds hashing above Int.MaxValue ..."
 *
 * Both sides assert the SAME seeds and the SAME expected tags. Neither table is
 * authoritative alone: a change to the hash must update the Go function, the Scala port,
 * and both tables in one commit. Do not "fix" a failure by editing the expectations.
 *
 * Why it matters: the leaf picks the tag and places the R=1 log stream on that node; the
 * SERVER independently recomputes the same tag from the same seed to store on the
 * `processrun` row (godev pkg/registry/database.go:81). A divergence silently records a
 * node the stream is not on.
 *
 * The expected values were generated by running the real Go function over these seeds.
 */
class PlacementTagForSeedTest extends AnyFunSuite with Matchers {

  import ContinuumRunnerClient.placementTagForSeed

  // seed -> (fnv1a-32 sum as produced by Go's hash/fnv, tag for a 3-node cluster)
  private val goldens: Seq[(String, Long, String)] = Seq(
    ("a", 3826002220L, "n2"),
    ("abc", 440920331L, "n3"),
    ("processrun-1", 3488657321L, "n3"),
    ("zzzz", 3781792677L, "n1"),
    ("0Xk2mQ", 2270264954L, "n3"),
    ("aBcDeF123456", 2246283413L, "n3"),
    ("01234567890123456789012345678901", 1152081613L, "n2"),
    ("ff", 1797453421L, "n2"),
    ("hello world", 3582672807L, "n1"),
    ("n1", 70638592L, "n2"),
    ("uid-with-dashes-9", 2780592793L, "n2"),
  )

  test("matches godev PlacementTagForSeed for a 3-node cluster") {
    goldens.foreach { case (seed, _, expected) =>
      withClue(s"seed=$seed: ") {
        placementTagForSeed(3, seed) shouldBe expected
      }
    }
  }

  /**
   * The regression this guards: Go's `int(h.Sum32())` on 64-bit is the UNSIGNED value, but
   * Scala's Int is signed 32-bit. "a" hashes to 3826002220, above Int.MaxValue — a naive
   * port yields a negative modulo and a tag like "n0" or "n-1". Every tag must be in n1..nN.
   */
  test("seeds hashing above Int.MaxValue still yield a tag in n1..nN") {
    val bigHashSeeds = goldens.filter(_._2 > Int.MaxValue.toLong).map(_._1)
    bigHashSeeds should not be empty // the corpus must actually exercise the overflow
    bigHashSeeds.foreach { seed =>
      withClue(s"seed=$seed: ") {
        placementTagForSeed(3, seed) should (be("n1") or be("n2") or be("n3"))
      }
    }
  }

  test("no placement on a single-node cluster or an empty seed") {
    placementTagForSeed(1, "anything") shouldBe ""
    placementTagForSeed(0, "anything") shouldBe ""
    placementTagForSeed(3, "") shouldBe ""
  }

  test("is deterministic and spreads across all nodes") {
    val uids = (1 to 300).map(i => s"processrun-uid-$i")
    uids.foreach(u => placementTagForSeed(3, u) shouldBe placementTagForSeed(3, u))
    uids.map(u => placementTagForSeed(3, u)).distinct.sorted shouldBe Seq("n1", "n2", "n3")
  }
}
