// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

@SerialVersionUID(0L)
final case class ChangeDataCaptureSubscription(
    id: _root_.scala.Predef.String = "",
    state: _root_.scala.Predef.String = "",
    matchers: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.RecordMatcher] = _root_.scala.Seq.empty,
    startSeq: _root_.scala.Predef.String = "",
    endSeq: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ChangeDataCaptureSubscription] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = state
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      matchers.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = startSeq
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = endSeq
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = state
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      matchers.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = startSeq
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = endSeq
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withId(__v: _root_.scala.Predef.String): ChangeDataCaptureSubscription = copy(id = __v)
    def withState(__v: _root_.scala.Predef.String): ChangeDataCaptureSubscription = copy(state = __v)
    def clearMatchers = copy(matchers = _root_.scala.Seq.empty)
    def addMatchers(__vs: a8.hermes.proto.process.wsmessages.RecordMatcher *): ChangeDataCaptureSubscription = addAllMatchers(__vs)
    def addAllMatchers(__vs: Iterable[a8.hermes.proto.process.wsmessages.RecordMatcher]): ChangeDataCaptureSubscription = copy(matchers = matchers ++ __vs)
    def withMatchers(__v: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.RecordMatcher]): ChangeDataCaptureSubscription = copy(matchers = __v)
    def withStartSeq(__v: _root_.scala.Predef.String): ChangeDataCaptureSubscription = copy(startSeq = __v)
    def withEndSeq(__v: _root_.scala.Predef.String): ChangeDataCaptureSubscription = copy(endSeq = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = state
          if (__t != "") __t else null
        }
        case 3 => matchers
        case 4 => {
          val __t = startSeq
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = endSeq
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(id)
        case 2 => _root_.scalapb.descriptors.PString(state)
        case 3 => _root_.scalapb.descriptors.PRepeated(matchers.iterator.map(_.toPMessage).toVector)
        case 4 => _root_.scalapb.descriptors.PString(startSeq)
        case 5 => _root_.scalapb.descriptors.PString(endSeq)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription.type = a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription
    // @@protoc_insertion_point(GeneratedMessage[mesh.ChangeDataCaptureSubscription])
}

object ChangeDataCaptureSubscription extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription = {
    var __id: _root_.scala.Predef.String = ""
    var __state: _root_.scala.Predef.String = ""
    val __matchers: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.process.wsmessages.RecordMatcher] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.process.wsmessages.RecordMatcher]
    var __startSeq: _root_.scala.Predef.String = ""
    var __endSeq: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __id = _input__.readStringRequireUtf8()
        case 18 =>
          __state = _input__.readStringRequireUtf8()
        case 26 =>
          __matchers += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.RecordMatcher](_input__)
        case 34 =>
          __startSeq = _input__.readStringRequireUtf8()
        case 42 =>
          __endSeq = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription(
        id = __id,
        state = __state,
        matchers = __matchers.result(),
        startSeq = __startSeq,
        endSeq = __endSeq,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription(
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        state = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        matchers = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.process.wsmessages.RecordMatcher]]).getOrElse(_root_.scala.Seq.empty),
        startSeq = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        endSeq = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WsmessagesProto.javaDescriptor.getMessageTypes().get(37)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WsmessagesProto.scalaDescriptor.messages(37)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = a8.hermes.proto.process.wsmessages.RecordMatcher
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription(
    id = "",
    state = "",
    matchers = _root_.scala.Seq.empty,
    startSeq = "",
    endSeq = ""
  )
  implicit class ChangeDataCaptureSubscriptionLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def state: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.state)((c_, f_) => c_.copy(state = f_))
    def matchers: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.process.wsmessages.RecordMatcher]] = field(_.matchers)((c_, f_) => c_.copy(matchers = f_))
    def startSeq: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.startSeq)((c_, f_) => c_.copy(startSeq = f_))
    def endSeq: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.endSeq)((c_, f_) => c_.copy(endSeq = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val STATE_FIELD_NUMBER = 2
  final val MATCHERS_FIELD_NUMBER = 3
  final val STARTSEQ_FIELD_NUMBER = 4
  final val ENDSEQ_FIELD_NUMBER = 5
  def of(
    id: _root_.scala.Predef.String,
    state: _root_.scala.Predef.String,
    matchers: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.RecordMatcher],
    startSeq: _root_.scala.Predef.String,
    endSeq: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription = _root_.a8.hermes.proto.process.wsmessages.ChangeDataCaptureSubscription(
    id,
    state,
    matchers,
    startSeq,
    endSeq
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[mesh.ChangeDataCaptureSubscription])
}
