// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

/** A node in the error tree. This composes recursively.
  *
  * Semantics:
  * - There is a single top-level ErrorNode for a logical error.
  * - Each ErrorNode has 0 or more "causes", each of which is itself an ErrorNode.
  *   This allows building a chain or tree of causes without special-casing.
  *
  * @param causes
  *   Zero or more direct causes of this error. Each cause is a full ErrorNode
  *   and can itself have further causes.
  */
@SerialVersionUID(0L)
final case class ErrorNode(
    frame: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorFrame] = _root_.scala.None,
    causes: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.ErrorNode] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ErrorNode] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (frame.isDefined) {
        val __value = frame.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      causes.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      frame.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      causes.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getFrame: a8.hermes.proto.process.wsmessages.ErrorFrame = frame.getOrElse(a8.hermes.proto.process.wsmessages.ErrorFrame.defaultInstance)
    def clearFrame: ErrorNode = copy(frame = _root_.scala.None)
    def withFrame(__v: a8.hermes.proto.process.wsmessages.ErrorFrame): ErrorNode = copy(frame = Option(__v))
    def clearCauses = copy(causes = _root_.scala.Seq.empty)
    def addCauses(__vs: a8.hermes.proto.process.wsmessages.ErrorNode *): ErrorNode = addAllCauses(__vs)
    def addAllCauses(__vs: Iterable[a8.hermes.proto.process.wsmessages.ErrorNode]): ErrorNode = copy(causes = causes ++ __vs)
    def withCauses(__v: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.ErrorNode]): ErrorNode = copy(causes = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => frame.orNull
        case 2 => causes
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => frame.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PRepeated(causes.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.wsmessages.ErrorNode.type = a8.hermes.proto.process.wsmessages.ErrorNode
    // @@protoc_insertion_point(GeneratedMessage[mesh.ErrorNode])
}

object ErrorNode extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.ErrorNode] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.ErrorNode] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.wsmessages.ErrorNode = {
    var __frame: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorFrame] = _root_.scala.None
    val __causes: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.process.wsmessages.ErrorNode] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.process.wsmessages.ErrorNode]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __frame = _root_.scala.Option(__frame.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.ErrorFrame](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __causes += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.ErrorNode](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.wsmessages.ErrorNode(
        frame = __frame,
        causes = __causes.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.wsmessages.ErrorNode] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.wsmessages.ErrorNode(
        frame = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorFrame]]),
        causes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.process.wsmessages.ErrorNode]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WsmessagesProto.javaDescriptor.getMessageTypes().get(14)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WsmessagesProto.scalaDescriptor.messages(14)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = a8.hermes.proto.process.wsmessages.ErrorFrame
      case 2 => __out = a8.hermes.proto.process.wsmessages.ErrorNode
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.process.wsmessages.ErrorNode(
    frame = _root_.scala.None,
    causes = _root_.scala.Seq.empty
  )
  implicit class ErrorNodeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorNode]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorNode](_l) {
    def frame: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorFrame] = field(_.getFrame)((c_, f_) => c_.copy(frame = _root_.scala.Option(f_)))
    def optionalFrame: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorFrame]] = field(_.frame)((c_, f_) => c_.copy(frame = f_))
    def causes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.process.wsmessages.ErrorNode]] = field(_.causes)((c_, f_) => c_.copy(causes = f_))
  }
  final val FRAME_FIELD_NUMBER = 1
  final val CAUSES_FIELD_NUMBER = 2
  def of(
    frame: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorFrame],
    causes: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.ErrorNode]
  ): _root_.a8.hermes.proto.process.wsmessages.ErrorNode = _root_.a8.hermes.proto.process.wsmessages.ErrorNode(
    frame,
    causes
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[mesh.ErrorNode])
}
