// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

/** One layer's view of an error.
  *
  * @param category
  *   High-level error category. Allowed values:
  *   "RPC", "AUTH", "CLIENT", "RESOURCE", "DEPENDENCY", "INTERNAL".
  * @param kind
  *   Category-local kind identifier. Allowed values per category include:
  *     RPC:        "BAD_REQUEST", "TIMEOUT", "CANCELLED"
  *     AUTH:       "UNAUTHENTICATED", "PERMISSION_DENIED"
  *     CLIENT:     "INVALID_ARGUMENT", "NOT_FOUND", "CONFLICT"
  *     RESOURCE:   "RATE_LIMITED", "QUOTA_EXCEEDED", "OVERLOADED"
  *     DEPENDENCY: "DB_UNAVAILABLE", "NATS_UNAVAILABLE", "UPSTREAM_UNAVAILABLE"
  *     INTERNAL:   "UNEXPECTED", "INVARIANT_VIOLATION"
  *   Additional kinds may be added over time but must preserve semantics.
  * @param message
  *   Human-readable message. Not for parsing.
  * @param retryable
  *   Whether a blind retry is reasonable without changing inputs.
  * @param details
  *   Free-form structured details (JSON-like). Use this instead of parsing "message".
  * @param component
  *   Logical component name, e.g. "user-service", "batch-worker".
  * @param location
  *   Optional source location for debugging.
  * @param timestamp
  *   Creation time (UTC).
  */
@SerialVersionUID(0L)
final case class ErrorFrame(
    category: _root_.scala.Predef.String = "",
    kind: _root_.scala.Predef.String = "",
    message: _root_.scala.Predef.String = "",
    retryable: _root_.scala.Boolean = false,
    details: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None,
    component: _root_.scala.Predef.String = "",
    location: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorLocation] = _root_.scala.None,
    timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ErrorFrame] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = category
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = kind
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = retryable
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(4, __value)
        }
      };
      if (details.isDefined) {
        val __value = details.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = component
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      if (location.isDefined) {
        val __value = location.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (timestamp.isDefined) {
        val __value = timestamp.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = category
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = kind
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = retryable
        if (__v != false) {
          _output__.writeBool(4, __v)
        }
      };
      details.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = component
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      location.foreach { __v =>
        val __m = __v
        _output__.writeTag(7, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      timestamp.foreach { __v =>
        val __m = __v
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withCategory(__v: _root_.scala.Predef.String): ErrorFrame = copy(category = __v)
    def withKind(__v: _root_.scala.Predef.String): ErrorFrame = copy(kind = __v)
    def withMessage(__v: _root_.scala.Predef.String): ErrorFrame = copy(message = __v)
    def withRetryable(__v: _root_.scala.Boolean): ErrorFrame = copy(retryable = __v)
    def getDetails: com.google.protobuf.struct.Struct = details.getOrElse(com.google.protobuf.struct.Struct.defaultInstance)
    def clearDetails: ErrorFrame = copy(details = _root_.scala.None)
    def withDetails(__v: com.google.protobuf.struct.Struct): ErrorFrame = copy(details = Option(__v))
    def withComponent(__v: _root_.scala.Predef.String): ErrorFrame = copy(component = __v)
    def getLocation: a8.hermes.proto.process.wsmessages.ErrorLocation = location.getOrElse(a8.hermes.proto.process.wsmessages.ErrorLocation.defaultInstance)
    def clearLocation: ErrorFrame = copy(location = _root_.scala.None)
    def withLocation(__v: a8.hermes.proto.process.wsmessages.ErrorLocation): ErrorFrame = copy(location = Option(__v))
    def getTimestamp: com.google.protobuf.timestamp.Timestamp = timestamp.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearTimestamp: ErrorFrame = copy(timestamp = _root_.scala.None)
    def withTimestamp(__v: com.google.protobuf.timestamp.Timestamp): ErrorFrame = copy(timestamp = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = category
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = kind
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = retryable
          if (__t != false) __t else null
        }
        case 5 => details.orNull
        case 6 => {
          val __t = component
          if (__t != "") __t else null
        }
        case 7 => location.orNull
        case 8 => timestamp.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(category)
        case 2 => _root_.scalapb.descriptors.PString(kind)
        case 3 => _root_.scalapb.descriptors.PString(message)
        case 4 => _root_.scalapb.descriptors.PBoolean(retryable)
        case 5 => details.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 6 => _root_.scalapb.descriptors.PString(component)
        case 7 => location.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 8 => timestamp.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.wsmessages.ErrorFrame.type = a8.hermes.proto.process.wsmessages.ErrorFrame
    // @@protoc_insertion_point(GeneratedMessage[mesh.ErrorFrame])
}

object ErrorFrame extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.ErrorFrame] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.ErrorFrame] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.wsmessages.ErrorFrame = {
    var __category: _root_.scala.Predef.String = ""
    var __kind: _root_.scala.Predef.String = ""
    var __message: _root_.scala.Predef.String = ""
    var __retryable: _root_.scala.Boolean = false
    var __details: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None
    var __component: _root_.scala.Predef.String = ""
    var __location: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorLocation] = _root_.scala.None
    var __timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __category = _input__.readStringRequireUtf8()
        case 18 =>
          __kind = _input__.readStringRequireUtf8()
        case 26 =>
          __message = _input__.readStringRequireUtf8()
        case 32 =>
          __retryable = _input__.readBool()
        case 42 =>
          __details = _root_.scala.Option(__details.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.struct.Struct](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 50 =>
          __component = _input__.readStringRequireUtf8()
        case 58 =>
          __location = _root_.scala.Option(__location.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.ErrorLocation](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 66 =>
          __timestamp = _root_.scala.Option(__timestamp.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.wsmessages.ErrorFrame(
        category = __category,
        kind = __kind,
        message = __message,
        retryable = __retryable,
        details = __details,
        component = __component,
        location = __location,
        timestamp = __timestamp,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.wsmessages.ErrorFrame] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.wsmessages.ErrorFrame(
        category = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        kind = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        retryable = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        details = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.struct.Struct]]),
        component = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        location = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorLocation]]),
        timestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WsmessagesProto.javaDescriptor.getMessageTypes().get(21)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WsmessagesProto.scalaDescriptor.messages(21)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 5 => __out = com.google.protobuf.struct.Struct
      case 7 => __out = a8.hermes.proto.process.wsmessages.ErrorLocation
      case 8 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.process.wsmessages.ErrorFrame(
    category = "",
    kind = "",
    message = "",
    retryable = false,
    details = _root_.scala.None,
    component = "",
    location = _root_.scala.None,
    timestamp = _root_.scala.None
  )
  implicit class ErrorFrameLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorFrame]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorFrame](_l) {
    def category: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.category)((c_, f_) => c_.copy(category = f_))
    def kind: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.kind)((c_, f_) => c_.copy(kind = f_))
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def retryable: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.retryable)((c_, f_) => c_.copy(retryable = f_))
    def details: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.struct.Struct] = field(_.getDetails)((c_, f_) => c_.copy(details = _root_.scala.Option(f_)))
    def optionalDetails: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.struct.Struct]] = field(_.details)((c_, f_) => c_.copy(details = f_))
    def component: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.component)((c_, f_) => c_.copy(component = f_))
    def location: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorLocation] = field(_.getLocation)((c_, f_) => c_.copy(location = _root_.scala.Option(f_)))
    def optionalLocation: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorLocation]] = field(_.location)((c_, f_) => c_.copy(location = f_))
    def timestamp: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getTimestamp)((c_, f_) => c_.copy(timestamp = _root_.scala.Option(f_)))
    def optionalTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
  }
  final val CATEGORY_FIELD_NUMBER = 1
  final val KIND_FIELD_NUMBER = 2
  final val MESSAGE_FIELD_NUMBER = 3
  final val RETRYABLE_FIELD_NUMBER = 4
  final val DETAILS_FIELD_NUMBER = 5
  final val COMPONENT_FIELD_NUMBER = 6
  final val LOCATION_FIELD_NUMBER = 7
  final val TIMESTAMP_FIELD_NUMBER = 8
  def of(
    category: _root_.scala.Predef.String,
    kind: _root_.scala.Predef.String,
    message: _root_.scala.Predef.String,
    retryable: _root_.scala.Boolean,
    details: _root_.scala.Option[com.google.protobuf.struct.Struct],
    component: _root_.scala.Predef.String,
    location: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorLocation],
    timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]
  ): _root_.a8.hermes.proto.process.wsmessages.ErrorFrame = _root_.a8.hermes.proto.process.wsmessages.ErrorFrame(
    category,
    kind,
    message,
    retryable,
    details,
    component,
    location,
    timestamp
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[mesh.ErrorFrame])
}
