// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

/** The coarse mailbox lifecycle. An enum rather than a string: the set is closed and the
  * server resolves it to concrete purge/close timeouts. UNSPECIFIED = the server default.
  */
sealed abstract class MailboxLifecycle(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = a8.hermes.proto.process.wsmessages.MailboxLifecycle
  type RecognizedType = a8.hermes.proto.process.wsmessages.MailboxLifecycle.Recognized
  def isMailboxLifecycleUnspecified: _root_.scala.Boolean = false
  def isShortLivedCli: _root_.scala.Boolean = false
  def isLongLivedDaemon: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[MailboxLifecycle] = a8.hermes.proto.process.wsmessages.MailboxLifecycle
  final def asRecognized: _root_.scala.Option[a8.hermes.proto.process.wsmessages.MailboxLifecycle.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[a8.hermes.proto.process.wsmessages.MailboxLifecycle.Recognized])
}

object MailboxLifecycle extends _root_.scalapb.GeneratedEnumCompanion[MailboxLifecycle] {
  sealed trait Recognized extends MailboxLifecycle
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[MailboxLifecycle] = this
  
  @SerialVersionUID(0L)
  case object MAILBOX_LIFECYCLE_UNSPECIFIED extends MailboxLifecycle(0) with MailboxLifecycle.Recognized {
    val index = 0
    val name = "MAILBOX_LIFECYCLE_UNSPECIFIED"
    override def isMailboxLifecycleUnspecified: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SHORT_LIVED_CLI extends MailboxLifecycle(1) with MailboxLifecycle.Recognized {
    val index = 1
    val name = "SHORT_LIVED_CLI"
    override def isShortLivedCli: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LONG_LIVED_DAEMON extends MailboxLifecycle(2) with MailboxLifecycle.Recognized {
    val index = 2
    val name = "LONG_LIVED_DAEMON"
    override def isLongLivedDaemon: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends MailboxLifecycle(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(MAILBOX_LIFECYCLE_UNSPECIFIED, SHORT_LIVED_CLI, LONG_LIVED_DAEMON)
  def fromValue(__value: _root_.scala.Int): MailboxLifecycle = __value match {
    case 0 => MAILBOX_LIFECYCLE_UNSPECIFIED
    case 1 => SHORT_LIVED_CLI
    case 2 => LONG_LIVED_DAEMON
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = WsmessagesProto.javaDescriptor.getEnumTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = WsmessagesProto.scalaDescriptor.enums(0)
}