// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

@SerialVersionUID(0L)
final case class Message(
    header: _root_.scala.Option[a8.hermes.proto.process.wsmessages.MessageHeader] = _root_.scala.None,
    senderEnvelope: _root_.scala.Option[a8.hermes.proto.process.wsmessages.SenderEnvelope] = _root_.scala.None,
    serverEnvelope: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ServerEnvelope] = _root_.scala.None,
    data: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    dataRef: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Message] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (header.isDefined) {
        val __value = header.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (senderEnvelope.isDefined) {
        val __value = senderEnvelope.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (serverEnvelope.isDefined) {
        val __value = serverEnvelope.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = data
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(4, __value)
        }
      };
      
      {
        val __value = dataRef
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      header.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      senderEnvelope.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      serverEnvelope.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = data
        if (!__v.isEmpty) {
          _output__.writeBytes(4, __v)
        }
      };
      {
        val __v = dataRef
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def getHeader: a8.hermes.proto.process.wsmessages.MessageHeader = header.getOrElse(a8.hermes.proto.process.wsmessages.MessageHeader.defaultInstance)
    def clearHeader: Message = copy(header = _root_.scala.None)
    def withHeader(__v: a8.hermes.proto.process.wsmessages.MessageHeader): Message = copy(header = Option(__v))
    def getSenderEnvelope: a8.hermes.proto.process.wsmessages.SenderEnvelope = senderEnvelope.getOrElse(a8.hermes.proto.process.wsmessages.SenderEnvelope.defaultInstance)
    def clearSenderEnvelope: Message = copy(senderEnvelope = _root_.scala.None)
    def withSenderEnvelope(__v: a8.hermes.proto.process.wsmessages.SenderEnvelope): Message = copy(senderEnvelope = Option(__v))
    def getServerEnvelope: a8.hermes.proto.process.wsmessages.ServerEnvelope = serverEnvelope.getOrElse(a8.hermes.proto.process.wsmessages.ServerEnvelope.defaultInstance)
    def clearServerEnvelope: Message = copy(serverEnvelope = _root_.scala.None)
    def withServerEnvelope(__v: a8.hermes.proto.process.wsmessages.ServerEnvelope): Message = copy(serverEnvelope = Option(__v))
    def withData(__v: _root_.com.google.protobuf.ByteString): Message = copy(data = __v)
    def withDataRef(__v: _root_.scala.Predef.String): Message = copy(dataRef = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => header.orNull
        case 2 => senderEnvelope.orNull
        case 3 => serverEnvelope.orNull
        case 4 => {
          val __t = data
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 5 => {
          val __t = dataRef
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => header.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => senderEnvelope.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => serverEnvelope.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => _root_.scalapb.descriptors.PByteString(data)
        case 5 => _root_.scalapb.descriptors.PString(dataRef)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.wsmessages.Message.type = a8.hermes.proto.process.wsmessages.Message
    // @@protoc_insertion_point(GeneratedMessage[hermes.Message])
}

object Message extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.Message] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.Message] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.wsmessages.Message = {
    var __header: _root_.scala.Option[a8.hermes.proto.process.wsmessages.MessageHeader] = _root_.scala.None
    var __senderEnvelope: _root_.scala.Option[a8.hermes.proto.process.wsmessages.SenderEnvelope] = _root_.scala.None
    var __serverEnvelope: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ServerEnvelope] = _root_.scala.None
    var __data: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
    var __dataRef: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __header = _root_.scala.Option(__header.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.MessageHeader](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __senderEnvelope = _root_.scala.Option(__senderEnvelope.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.SenderEnvelope](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __serverEnvelope = _root_.scala.Option(__serverEnvelope.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.ServerEnvelope](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 34 =>
          __data = _input__.readBytes()
        case 42 =>
          __dataRef = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.wsmessages.Message(
        header = __header,
        senderEnvelope = __senderEnvelope,
        serverEnvelope = __serverEnvelope,
        data = __data,
        dataRef = __dataRef,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.wsmessages.Message] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.wsmessages.Message(
        header = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.wsmessages.MessageHeader]]),
        senderEnvelope = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.wsmessages.SenderEnvelope]]),
        serverEnvelope = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.wsmessages.ServerEnvelope]]),
        data = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        dataRef = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WsmessagesProto.javaDescriptor.getMessageTypes().get(14)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WsmessagesProto.scalaDescriptor.messages(14)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = a8.hermes.proto.process.wsmessages.MessageHeader
      case 2 => __out = a8.hermes.proto.process.wsmessages.SenderEnvelope
      case 3 => __out = a8.hermes.proto.process.wsmessages.ServerEnvelope
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.process.wsmessages.Message(
    header = _root_.scala.None,
    senderEnvelope = _root_.scala.None,
    serverEnvelope = _root_.scala.None,
    data = _root_.com.google.protobuf.ByteString.EMPTY,
    dataRef = ""
  )
  implicit class MessageLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.Message]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.wsmessages.Message](_l) {
    def header: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.MessageHeader] = field(_.getHeader)((c_, f_) => c_.copy(header = _root_.scala.Option(f_)))
    def optionalHeader: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.wsmessages.MessageHeader]] = field(_.header)((c_, f_) => c_.copy(header = f_))
    def senderEnvelope: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.SenderEnvelope] = field(_.getSenderEnvelope)((c_, f_) => c_.copy(senderEnvelope = _root_.scala.Option(f_)))
    def optionalSenderEnvelope: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.wsmessages.SenderEnvelope]] = field(_.senderEnvelope)((c_, f_) => c_.copy(senderEnvelope = f_))
    def serverEnvelope: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ServerEnvelope] = field(_.getServerEnvelope)((c_, f_) => c_.copy(serverEnvelope = _root_.scala.Option(f_)))
    def optionalServerEnvelope: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.wsmessages.ServerEnvelope]] = field(_.serverEnvelope)((c_, f_) => c_.copy(serverEnvelope = f_))
    def data: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.data)((c_, f_) => c_.copy(data = f_))
    def dataRef: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.dataRef)((c_, f_) => c_.copy(dataRef = f_))
  }
  final val HEADER_FIELD_NUMBER = 1
  final val SENDERENVELOPE_FIELD_NUMBER = 2
  final val SERVERENVELOPE_FIELD_NUMBER = 3
  final val DATA_FIELD_NUMBER = 4
  final val DATAREF_FIELD_NUMBER = 5
  def of(
    header: _root_.scala.Option[a8.hermes.proto.process.wsmessages.MessageHeader],
    senderEnvelope: _root_.scala.Option[a8.hermes.proto.process.wsmessages.SenderEnvelope],
    serverEnvelope: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ServerEnvelope],
    data: _root_.com.google.protobuf.ByteString,
    dataRef: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.process.wsmessages.Message = _root_.a8.hermes.proto.process.wsmessages.Message(
    header,
    senderEnvelope,
    serverEnvelope,
    data,
    dataRef
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[hermes.Message])
}
