// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

/** Error info attached to an RpcHeader when frameType == ErrorResponse.
  *
  * For backward compatibility, the legacy fields (errorCode, message, stackTrace) are preserved.
  * New code SHOULD use error_node instead.
  *
  * - errorCode, message, stackTrace: legacy fields (deprecated but functional)
  * - error_node: new preferred format with rich error tree structure
  *
  * @param errorCode
  *   Legacy fields (deprecated but maintained for backward compatibility)
  * @param errorNode
  *   New error model (preferred) - single error with optional causes
  */
@SerialVersionUID(0L)
final case class RpcErrorInfo(
    errorCode: _root_.scala.Int = 0,
    message: _root_.scala.Predef.String = "",
    stackTrace: _root_.scala.Predef.String = "",
    errorNode: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorNode] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[RpcErrorInfo] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = errorCode
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = stackTrace
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      if (errorNode.isDefined) {
        val __value = errorNode.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = errorCode
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = stackTrace
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      errorNode.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withErrorCode(__v: _root_.scala.Int): RpcErrorInfo = copy(errorCode = __v)
    def withMessage(__v: _root_.scala.Predef.String): RpcErrorInfo = copy(message = __v)
    def withStackTrace(__v: _root_.scala.Predef.String): RpcErrorInfo = copy(stackTrace = __v)
    def getErrorNode: a8.hermes.proto.process.wsmessages.ErrorNode = errorNode.getOrElse(a8.hermes.proto.process.wsmessages.ErrorNode.defaultInstance)
    def clearErrorNode: RpcErrorInfo = copy(errorNode = _root_.scala.None)
    def withErrorNode(__v: a8.hermes.proto.process.wsmessages.ErrorNode): RpcErrorInfo = copy(errorNode = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = errorCode
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = stackTrace
          if (__t != "") __t else null
        }
        case 4 => errorNode.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(errorCode)
        case 2 => _root_.scalapb.descriptors.PString(message)
        case 3 => _root_.scalapb.descriptors.PString(stackTrace)
        case 4 => errorNode.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.wsmessages.RpcErrorInfo.type = a8.hermes.proto.process.wsmessages.RpcErrorInfo
    // @@protoc_insertion_point(GeneratedMessage[mesh.RpcErrorInfo])
}

object RpcErrorInfo extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.RpcErrorInfo] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.RpcErrorInfo] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.wsmessages.RpcErrorInfo = {
    var __errorCode: _root_.scala.Int = 0
    var __message: _root_.scala.Predef.String = ""
    var __stackTrace: _root_.scala.Predef.String = ""
    var __errorNode: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorNode] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __errorCode = _input__.readUInt32()
        case 18 =>
          __message = _input__.readStringRequireUtf8()
        case 26 =>
          __stackTrace = _input__.readStringRequireUtf8()
        case 34 =>
          __errorNode = _root_.scala.Option(__errorNode.fold(_root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.ErrorNode](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.wsmessages.RpcErrorInfo(
        errorCode = __errorCode,
        message = __message,
        stackTrace = __stackTrace,
        errorNode = __errorNode,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.wsmessages.RpcErrorInfo] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.wsmessages.RpcErrorInfo(
        errorCode = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        stackTrace = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        errorNode = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorNode]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WsmessagesProto.javaDescriptor.getMessageTypes().get(23)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WsmessagesProto.scalaDescriptor.messages(23)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = a8.hermes.proto.process.wsmessages.ErrorNode
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.process.wsmessages.RpcErrorInfo(
    errorCode = 0,
    message = "",
    stackTrace = "",
    errorNode = _root_.scala.None
  )
  implicit class RpcErrorInfoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.RpcErrorInfo]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.wsmessages.RpcErrorInfo](_l) {
    def errorCode: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.errorCode)((c_, f_) => c_.copy(errorCode = f_))
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def stackTrace: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.stackTrace)((c_, f_) => c_.copy(stackTrace = f_))
    def errorNode: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.ErrorNode] = field(_.getErrorNode)((c_, f_) => c_.copy(errorNode = _root_.scala.Option(f_)))
    def optionalErrorNode: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorNode]] = field(_.errorNode)((c_, f_) => c_.copy(errorNode = f_))
  }
  final val ERRORCODE_FIELD_NUMBER = 1
  final val MESSAGE_FIELD_NUMBER = 2
  final val STACKTRACE_FIELD_NUMBER = 3
  final val ERROR_NODE_FIELD_NUMBER = 4
  def of(
    errorCode: _root_.scala.Int,
    message: _root_.scala.Predef.String,
    stackTrace: _root_.scala.Predef.String,
    errorNode: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ErrorNode]
  ): _root_.a8.hermes.proto.process.wsmessages.RpcErrorInfo = _root_.a8.hermes.proto.process.wsmessages.RpcErrorInfo(
    errorCode,
    message,
    stackTrace,
    errorNode
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[mesh.RpcErrorInfo])
}
