// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

@SerialVersionUID(0L)
final case class SubscribeResponse(
    succeeded: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    errors: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.SubscribeError] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SubscribeResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      succeeded.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
      }
      errors.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      succeeded.foreach { __v =>
        val __m = __v
        _output__.writeString(1, __m)
      };
      errors.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearSucceeded = copy(succeeded = _root_.scala.Seq.empty)
    def addSucceeded(__vs: _root_.scala.Predef.String *): SubscribeResponse = addAllSucceeded(__vs)
    def addAllSucceeded(__vs: Iterable[_root_.scala.Predef.String]): SubscribeResponse = copy(succeeded = succeeded ++ __vs)
    def withSucceeded(__v: _root_.scala.Seq[_root_.scala.Predef.String]): SubscribeResponse = copy(succeeded = __v)
    def clearErrors = copy(errors = _root_.scala.Seq.empty)
    def addErrors(__vs: a8.hermes.proto.process.wsmessages.SubscribeError *): SubscribeResponse = addAllErrors(__vs)
    def addAllErrors(__vs: Iterable[a8.hermes.proto.process.wsmessages.SubscribeError]): SubscribeResponse = copy(errors = errors ++ __vs)
    def withErrors(__v: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.SubscribeError]): SubscribeResponse = copy(errors = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => succeeded
        case 2 => errors
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(succeeded.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 2 => _root_.scalapb.descriptors.PRepeated(errors.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.wsmessages.SubscribeResponse.type = a8.hermes.proto.process.wsmessages.SubscribeResponse
    // @@protoc_insertion_point(GeneratedMessage[mesh.SubscribeResponse])
}

object SubscribeResponse extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.SubscribeResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.wsmessages.SubscribeResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.wsmessages.SubscribeResponse = {
    val __succeeded: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    val __errors: _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.process.wsmessages.SubscribeError] = new _root_.scala.collection.immutable.VectorBuilder[a8.hermes.proto.process.wsmessages.SubscribeError]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __succeeded += _input__.readStringRequireUtf8()
        case 18 =>
          __errors += _root_.scalapb.LiteParser.readMessage[a8.hermes.proto.process.wsmessages.SubscribeError](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.wsmessages.SubscribeResponse(
        succeeded = __succeeded.result(),
        errors = __errors.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.wsmessages.SubscribeResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.wsmessages.SubscribeResponse(
        succeeded = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        errors = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[a8.hermes.proto.process.wsmessages.SubscribeError]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WsmessagesProto.javaDescriptor.getMessageTypes().get(23)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WsmessagesProto.scalaDescriptor.messages(23)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = a8.hermes.proto.process.wsmessages.SubscribeError
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.process.wsmessages.SubscribeResponse(
    succeeded = _root_.scala.Seq.empty,
    errors = _root_.scala.Seq.empty
  )
  implicit class SubscribeResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.wsmessages.SubscribeResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.wsmessages.SubscribeResponse](_l) {
    def succeeded: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.succeeded)((c_, f_) => c_.copy(succeeded = f_))
    def errors: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[a8.hermes.proto.process.wsmessages.SubscribeError]] = field(_.errors)((c_, f_) => c_.copy(errors = f_))
  }
  final val SUCCEEDED_FIELD_NUMBER = 1
  final val ERRORS_FIELD_NUMBER = 2
  def of(
    succeeded: _root_.scala.Seq[_root_.scala.Predef.String],
    errors: _root_.scala.Seq[a8.hermes.proto.process.wsmessages.SubscribeError]
  ): _root_.a8.hermes.proto.process.wsmessages.SubscribeResponse = _root_.a8.hermes.proto.process.wsmessages.SubscribeResponse(
    succeeded,
    errors
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[mesh.SubscribeResponse])
}
