// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.discovery.discovery

/** LocationQuery filters by deployment location
  */
@SerialVersionUID(0L)
final case class LocationQuery(
    server: _root_.scala.Predef.String = "",
    user: _root_.scala.Predef.String = "",
    userServer: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[LocationQuery] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = server
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = user
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = userServer
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = server
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = user
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = userServer
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withServer(__v: _root_.scala.Predef.String): LocationQuery = copy(server = __v)
    def withUser(__v: _root_.scala.Predef.String): LocationQuery = copy(user = __v)
    def withUserServer(__v: _root_.scala.Predef.String): LocationQuery = copy(userServer = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = server
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = user
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = userServer
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(server)
        case 2 => _root_.scalapb.descriptors.PString(user)
        case 3 => _root_.scalapb.descriptors.PString(userServer)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.discovery.discovery.LocationQuery.type = a8.hermes.proto.discovery.discovery.LocationQuery
    // @@protoc_insertion_point(GeneratedMessage[discovery.LocationQuery])
}

object LocationQuery extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.discovery.discovery.LocationQuery] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.discovery.discovery.LocationQuery] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.discovery.discovery.LocationQuery = {
    var __server: _root_.scala.Predef.String = ""
    var __user: _root_.scala.Predef.String = ""
    var __userServer: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __server = _input__.readStringRequireUtf8()
        case 18 =>
          __user = _input__.readStringRequireUtf8()
        case 26 =>
          __userServer = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.discovery.discovery.LocationQuery(
        server = __server,
        user = __user,
        userServer = __userServer,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.discovery.discovery.LocationQuery] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.discovery.discovery.LocationQuery(
        server = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        user = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        userServer = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = DiscoveryProto.javaDescriptor.getMessageTypes().get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = DiscoveryProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.discovery.discovery.LocationQuery(
    server = "",
    user = "",
    userServer = ""
  )
  implicit class LocationQueryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.discovery.discovery.LocationQuery]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.discovery.discovery.LocationQuery](_l) {
    def server: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.server)((c_, f_) => c_.copy(server = f_))
    def user: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.user)((c_, f_) => c_.copy(user = f_))
    def userServer: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.userServer)((c_, f_) => c_.copy(userServer = f_))
  }
  final val SERVER_FIELD_NUMBER = 1
  final val USER_FIELD_NUMBER = 2
  final val USER_SERVER_FIELD_NUMBER = 3
  def of(
    server: _root_.scala.Predef.String,
    user: _root_.scala.Predef.String,
    userServer: _root_.scala.Predef.String
  ): _root_.a8.hermes.proto.discovery.discovery.LocationQuery = _root_.a8.hermes.proto.discovery.discovery.LocationQuery(
    server,
    user,
    userServer
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[discovery.LocationQuery])
}
