
// 
// DO NOT EDIT THIS FILE IT IS MACHINE GENERATED
// 
// This file is generated from modules.conf using `a8-versions build_dot_sbt`
// 
// It was generated at 2022-01-12 11:25:34.837 -0600 by raph on ENNS-PC
// 
// a8-versions build/versioning info follows
// 
//        build_date : Thu Sep 30 12:56:07 CDT 2021
//        build_machine : ENNS-PC
//        build_machine_ip : 127.0.1.1
//        build_java_version : 11.0.11
//        build_user : raph
//        version_number : 1.0.0-20210930_1255_master
//        project_name : a8-versions
//        build_os : Linux
// 
//      

addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.9")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")

addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.6.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.0-RC6")
//addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")

//libraryDependencies += "org.slf4j" % "slf4j-nop" % "1.7.21"
//addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")

// use this one if you need dobby
//addSbtPlugin("a8" % "sbt-a8" % "1.1.0-20210702_1452")
addSbtPlugin("io.accur8" % "sbt-a8" % "1.2.0-20220113_1040")
