// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.process_rpc

/** @param status
  *   Status of this specific check
  * @param message
  *   Details about this check
  * @param duration
  *   Duration in milliseconds
  */
@SerialVersionUID(0L)
final case class HealthCheckResult(
    status: a8.hermes.proto.process.process_rpc.HealthStatus = a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED,
    message: _root_.scala.Predef.String = "",
    duration: _root_.scala.Long = 0L,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[HealthCheckResult] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = status.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(1, __value)
        }
      };
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = duration
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = status.value
        if (__v != 0) {
          _output__.writeEnum(1, __v)
        }
      };
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = duration
        if (__v != 0L) {
          _output__.writeInt64(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withStatus(__v: a8.hermes.proto.process.process_rpc.HealthStatus): HealthCheckResult = copy(status = __v)
    def withMessage(__v: _root_.scala.Predef.String): HealthCheckResult = copy(message = __v)
    def withDuration(__v: _root_.scala.Long): HealthCheckResult = copy(duration = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = status.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 2 => {
          val __t = message
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = duration
          if (__t != 0L) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PEnum(status.scalaValueDescriptor)
        case 2 => _root_.scalapb.descriptors.PString(message)
        case 3 => _root_.scalapb.descriptors.PLong(duration)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.process.process_rpc.HealthCheckResult.type = a8.hermes.proto.process.process_rpc.HealthCheckResult
    // @@protoc_insertion_point(GeneratedMessage[process_rpc.HealthCheckResult])
}

object HealthCheckResult extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.HealthCheckResult] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.process.process_rpc.HealthCheckResult] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.process.process_rpc.HealthCheckResult = {
    var __status: a8.hermes.proto.process.process_rpc.HealthStatus = a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED
    var __message: _root_.scala.Predef.String = ""
    var __duration: _root_.scala.Long = 0L
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __status = a8.hermes.proto.process.process_rpc.HealthStatus.fromValue(_input__.readEnum())
        case 18 =>
          __message = _input__.readStringRequireUtf8()
        case 24 =>
          __duration = _input__.readInt64()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.process.process_rpc.HealthCheckResult(
        status = __status,
        message = __message,
        duration = __duration,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.process.process_rpc.HealthCheckResult] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.process.process_rpc.HealthCheckResult(
        status = a8.hermes.proto.process.process_rpc.HealthStatus.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED.scalaValueDescriptor).number),
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        duration = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Long]).getOrElse(0L)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ProcessRpcProto.javaDescriptor.getMessageTypes().get(9)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ProcessRpcProto.scalaDescriptor.messages(9)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => a8.hermes.proto.process.process_rpc.HealthStatus
    }
  }
  lazy val defaultInstance = a8.hermes.proto.process.process_rpc.HealthCheckResult(
    status = a8.hermes.proto.process.process_rpc.HealthStatus.HEALTH_STATUS_UNSPECIFIED,
    message = "",
    duration = 0L
  )
  implicit class HealthCheckResultLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResult]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.process.process_rpc.HealthCheckResult](_l) {
    def status: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.process.process_rpc.HealthStatus] = field(_.status)((c_, f_) => c_.copy(status = f_))
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
    def duration: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.duration)((c_, f_) => c_.copy(duration = f_))
  }
  final val STATUS_FIELD_NUMBER = 1
  final val MESSAGE_FIELD_NUMBER = 2
  final val DURATION_FIELD_NUMBER = 3
  def of(
    status: a8.hermes.proto.process.process_rpc.HealthStatus,
    message: _root_.scala.Predef.String,
    duration: _root_.scala.Long
  ): _root_.a8.hermes.proto.process.process_rpc.HealthCheckResult = _root_.a8.hermes.proto.process.process_rpc.HealthCheckResult(
    status,
    message,
    duration
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[process_rpc.HealthCheckResult])
}
