// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.process.wsmessages

sealed abstract class ContentType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = a8.hermes.proto.process.wsmessages.ContentType
  type RecognizedType = a8.hermes.proto.process.wsmessages.ContentType.Recognized
  def isUnspecifiedCt: _root_.scala.Boolean = false
  def isProtobuf: _root_.scala.Boolean = false
  def isJson: _root_.scala.Boolean = false
  def isBinary: _root_.scala.Boolean = false
  def isText: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[ContentType] = a8.hermes.proto.process.wsmessages.ContentType
  final def asRecognized: _root_.scala.Option[a8.hermes.proto.process.wsmessages.ContentType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[a8.hermes.proto.process.wsmessages.ContentType.Recognized])
}

object ContentType extends _root_.scalapb.GeneratedEnumCompanion[ContentType] {
  sealed trait Recognized extends ContentType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ContentType] = this
  
  @SerialVersionUID(0L)
  case object UnspecifiedCT extends ContentType(0) with ContentType.Recognized {
    val index = 0
    val name = "UnspecifiedCT"
    override def isUnspecifiedCt: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Protobuf extends ContentType(1) with ContentType.Recognized {
    val index = 1
    val name = "Protobuf"
    override def isProtobuf: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Json extends ContentType(2) with ContentType.Recognized {
    val index = 2
    val name = "Json"
    override def isJson: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Binary extends ContentType(3) with ContentType.Recognized {
    val index = 3
    val name = "Binary"
    override def isBinary: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Text extends ContentType(4) with ContentType.Recognized {
    val index = 4
    val name = "Text"
    override def isText: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends ContentType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UnspecifiedCT, Protobuf, Json, Binary, Text)
  def fromValue(__value: _root_.scala.Int): ContentType = __value match {
    case 0 => UnspecifiedCT
    case 1 => Protobuf
    case 2 => Json
    case 3 => Binary
    case 4 => Text
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = WsmessagesProto.javaDescriptor.getEnumTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = WsmessagesProto.scalaDescriptor.enums(1)
}