// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.mailbox.mailbox

/** NamedMailboxInfo contains info about a named mailbox
  */
@SerialVersionUID(0L)
final case class NamedMailboxInfo(
    address: _root_.scala.Predef.String = "",
    created: _root_.scala.Long = 0L,
    lastActivity: _root_.scala.Long = 0L,
    channels: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[NamedMailboxInfo] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = address
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = created
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(2, __value)
        }
      };
      
      {
        val __value = lastActivity
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(3, __value)
        }
      };
      channels.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = address
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = created
        if (__v != 0L) {
          _output__.writeInt64(2, __v)
        }
      };
      {
        val __v = lastActivity
        if (__v != 0L) {
          _output__.writeInt64(3, __v)
        }
      };
      channels.foreach { __v =>
        val __m = __v
        _output__.writeString(4, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def withAddress(__v: _root_.scala.Predef.String): NamedMailboxInfo = copy(address = __v)
    def withCreated(__v: _root_.scala.Long): NamedMailboxInfo = copy(created = __v)
    def withLastActivity(__v: _root_.scala.Long): NamedMailboxInfo = copy(lastActivity = __v)
    def clearChannels = copy(channels = _root_.scala.Seq.empty)
    def addChannels(__vs: _root_.scala.Predef.String *): NamedMailboxInfo = addAllChannels(__vs)
    def addAllChannels(__vs: Iterable[_root_.scala.Predef.String]): NamedMailboxInfo = copy(channels = channels ++ __vs)
    def withChannels(__v: _root_.scala.Seq[_root_.scala.Predef.String]): NamedMailboxInfo = copy(channels = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = address
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = created
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = lastActivity
          if (__t != 0L) __t else null
        }
        case 4 => channels
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(address)
        case 2 => _root_.scalapb.descriptors.PLong(created)
        case 3 => _root_.scalapb.descriptors.PLong(lastActivity)
        case 4 => _root_.scalapb.descriptors.PRepeated(channels.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo.type = a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo
    // @@protoc_insertion_point(GeneratedMessage[mailbox.NamedMailboxInfo])
}

object NamedMailboxInfo extends scalapb.GeneratedMessageCompanion[a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo = {
    var __address: _root_.scala.Predef.String = ""
    var __created: _root_.scala.Long = 0L
    var __lastActivity: _root_.scala.Long = 0L
    val __channels: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __address = _input__.readStringRequireUtf8()
        case 16 =>
          __created = _input__.readInt64()
        case 24 =>
          __lastActivity = _input__.readInt64()
        case 34 =>
          __channels += _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo(
        address = __address,
        created = __created,
        lastActivity = __lastActivity,
        channels = __channels.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo(
        address = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        created = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        lastActivity = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        channels = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = MailboxProto.javaDescriptor.getMessageTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = MailboxProto.scalaDescriptor.messages(7)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo(
    address = "",
    created = 0L,
    lastActivity = 0L,
    channels = _root_.scala.Seq.empty
  )
  implicit class NamedMailboxInfoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo](_l) {
    def address: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.address)((c_, f_) => c_.copy(address = f_))
    def created: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.created)((c_, f_) => c_.copy(created = f_))
    def lastActivity: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.lastActivity)((c_, f_) => c_.copy(lastActivity = f_))
    def channels: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.channels)((c_, f_) => c_.copy(channels = f_))
  }
  final val ADDRESS_FIELD_NUMBER = 1
  final val CREATED_FIELD_NUMBER = 2
  final val LAST_ACTIVITY_FIELD_NUMBER = 3
  final val CHANNELS_FIELD_NUMBER = 4
  def of(
    address: _root_.scala.Predef.String,
    created: _root_.scala.Long,
    lastActivity: _root_.scala.Long,
    channels: _root_.scala.Seq[_root_.scala.Predef.String]
  ): _root_.a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo = _root_.a8.hermes.proto.mailbox.mailbox.NamedMailboxInfo(
    address,
    created,
    lastActivity,
    channels
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[mailbox.NamedMailboxInfo])
}
