name: Build and Deploy Documentation

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - '**.md'
      - 'build.sbt'
      - 'documentation.sbt'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for git info
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache SBT
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
    
    - name: Generate Documentation
      run: |
        sbt clean compile
        sbt generateDocs
      env:
        SBT_OPTS: "-Xmx4G -XX:+UseG1GC"
    
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: target/site/
        retention-days: 7
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
        cname: accur8-sync.github.io  # Optional: custom domain
        force_orphan: true

  validate-examples:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Validate Example Code
      run: |
        sbt "compile"
        # Compile examples to ensure they're valid
        find examples -name "*.scala" -exec scalac -cp "$(sbt -error 'export compile:dependencyClasspath' | tail -n 1)" {} +