// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package a8.hermes.proto.db.db

object DbProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.struct.StructProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      a8.hermes.proto.db.db.QueryRequest,
      a8.hermes.proto.db.db.QueryResponse,
      a8.hermes.proto.db.db.FetchRequest,
      a8.hermes.proto.db.db.FetchResponse,
      a8.hermes.proto.db.db.InsertRequest,
      a8.hermes.proto.db.db.InsertResponse,
      a8.hermes.proto.db.db.UpdateRequest,
      a8.hermes.proto.db.db.UpdateResponse,
      a8.hermes.proto.db.db.DeleteRequest,
      a8.hermes.proto.db.db.DeleteResponse,
      a8.hermes.proto.db.db.SqlError
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CghkYi5wcm90bxICZGIaHGdvb2dsZS9wcm90b2J1Zi9zdHJ1Y3QucHJvdG8iigIKDFF1ZXJ5UmVxdWVzdBItCgp0YWJsZV9uY
  W1lGAEgASgJQg7iPwsSCXRhYmxlTmFtZVIJdGFibGVOYW1lEiYKB2NvbHVtbnMYAiADKAlCDOI/CRIHY29sdW1uc1IHY29sdW1uc
  xIzCgx3aGVyZV9jbGF1c2UYAyABKAlCEOI/DRILd2hlcmVDbGF1c2VSC3doZXJlQ2xhdXNlEicKCG9yZGVyX2J5GAQgAygJQgziP
  wkSB29yZGVyQnlSB29yZGVyQnkSIAoFbGltaXQYBSABKAVCCuI/BxIFbGltaXRSBWxpbWl0EiMKBm9mZnNldBgGIAEoBUIL4j8IE
  gZvZmZzZXRSBm9mZnNldCJzCg1RdWVyeVJlc3BvbnNlEjYKBHJvd3MYASADKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0QgniP
  wYSBHJvd3NSBHJvd3MSKgoJcm93X2NvdW50GAIgASgFQg3iPwoSCHJvd0NvdW50Ughyb3dDb3VudCKaAQoMRmV0Y2hSZXF1ZXN0E
  i0KCnRhYmxlX25hbWUYASABKAlCDuI/CxIJdGFibGVOYW1lUgl0YWJsZU5hbWUSMwoDa2V5GAIgASgLMhcuZ29vZ2xlLnByb3RvY
  nVmLlN0cnVjdEII4j8FEgNrZXlSA2tleRImCgdjb2x1bW5zGAMgAygJQgziPwkSB2NvbHVtbnNSB2NvbHVtbnMiZgoNRmV0Y2hSZ
  XNwb25zZRIzCgNyb3cYASABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0QgjiPwUSA3Jvd1IDcm93EiAKBWZvdW5kGAIgASgIQ
  griPwcSBWZvdW5kUgVmb3VuZCKrAQoNSW5zZXJ0UmVxdWVzdBItCgp0YWJsZV9uYW1lGAEgASgJQg7iPwsSCXRhYmxlTmFtZVIJd
  GFibGVOYW1lEjwKBnZhbHVlcxgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCC+I/CBIGdmFsdWVzUgZ2YWx1ZXMSLQoKc
  mV0dXJuX3JvdxgDIAEoCEIO4j8LEglyZXR1cm5Sb3dSCXJldHVyblJvdyKdAQoOSW5zZXJ0UmVzcG9uc2USJgoHc3VjY2VzcxgBI
  AEoCEIM4j8JEgdzdWNjZXNzUgdzdWNjZXNzEjMKA3JvdxgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCCOI/BRIDcm93U
  gNyb3cSLgoFZXJyb3IYAyABKAsyDC5kYi5TcWxFcnJvckIK4j8HEgVlcnJvclIFZXJyb3Ii4AEKDVVwZGF0ZVJlcXVlc3QSLQoKd
  GFibGVfbmFtZRgBIAEoCUIO4j8LEgl0YWJsZU5hbWVSCXRhYmxlTmFtZRIzCgNrZXkYAiABKAsyFy5nb29nbGUucHJvdG9idWYuU
  3RydWN0QgjiPwUSA2tleVIDa2V5EjwKBnZhbHVlcxgDIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCC+I/CBIGdmFsdWVzU
  gZ2YWx1ZXMSLQoKcmV0dXJuX3JvdxgEIAEoCEIO4j8LEglyZXR1cm5Sb3dSCXJldHVyblJvdyLVAQoOVXBkYXRlUmVzcG9uc2USJ
  goHc3VjY2VzcxgBIAEoCEIM4j8JEgdzdWNjZXNzUgdzdWNjZXNzEjMKA3JvdxgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y
  3RCCOI/BRIDcm93UgNyb3cSNgoNcm93c19hZmZlY3RlZBgDIAEoBUIR4j8OEgxyb3dzQWZmZWN0ZWRSDHJvd3NBZmZlY3RlZBIuC
  gVlcnJvchgEIAEoCzIMLmRiLlNxbEVycm9yQgriPwcSBWVycm9yUgVlcnJvciKlAQoNRGVsZXRlUmVxdWVzdBItCgp0YWJsZV9uY
  W1lGAEgASgJQg7iPwsSCXRhYmxlTmFtZVIJdGFibGVOYW1lEjMKA2tleRgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RCC
  OI/BRIDa2V5UgNrZXkSMAoLc29mdF9kZWxldGUYAyABKAhCD+I/DBIKc29mdERlbGV0ZVIKc29mdERlbGV0ZSKgAQoORGVsZXRlU
  mVzcG9uc2USJgoHc3VjY2VzcxgBIAEoCEIM4j8JEgdzdWNjZXNzUgdzdWNjZXNzEjYKDXJvd3NfYWZmZWN0ZWQYAiABKAVCEeI/D
  hIMcm93c0FmZmVjdGVkUgxyb3dzQWZmZWN0ZWQSLgoFZXJyb3IYAyABKAsyDC5kYi5TcWxFcnJvckIK4j8HEgVlcnJvclIFZXJyb
  3Ii5QEKCFNxbEVycm9yEiYKB21lc3NhZ2UYASABKAlCDOI/CRIHbWVzc2FnZVIHbWVzc2FnZRI0Cg1wZ19lcnJvcl9jb2RlGAIgA
  SgJQhDiPw0SC3BnRXJyb3JDb2RlUgtwZ0Vycm9yQ29kZRI9ChBwZ19lcnJvcl9tZXNzYWdlGAMgASgJQhPiPxASDnBnRXJyb3JNZ
  XNzYWdlUg5wZ0Vycm9yTWVzc2FnZRI8Cg9jb25zdHJhaW50X25hbWUYBCABKAlCE+I/EBIOY29uc3RyYWludE5hbWVSDmNvbnN0c
  mFpbnROYW1lQjIKEmE4Lmhlcm1lcy5wcm90by5kYlABWhphY2N1cjguaW8vZ29kZXYvcGtnL3JwYy9kYmIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      com.google.protobuf.struct.StructProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}